// 실행판(docs/plan/phase1-todo.md) GATE 의 검사 정의. 검사 추가는 이 데이터만 고친다.
// 검사가 빈 단계는 gate 가 실행·봉인을 거부한다. 각 단계 검사는 그 단계를 시작할 때 실행판 GATE 표대로 채운다.
// outputs 는 --assert-order 가 잠긴 단계의 변경을 잡는 데 쓰는 글롭이다.
// requires: ["local-services"] 는 이 컴퓨터에서만 띄워 둔 서비스가 필요한 검사다 (시험용 OmniRoute·Keycloak·
// mailpit, docker 테스트 DB). CI 의 봉인 재검(gate.yml)은 --skip-requires local-services 로 이 검사를 건너뛰고,
// CI 매트릭스(ci.yml, S7.T1)가 단계마다 서비스를 띄운 잡에서 node scripts/gate.mjs S<n> 으로 다시 돈다.

const nodeTest = (file, tc) => `node --test --test-reporter=tap --test-name-pattern="${tc}" ${file}`;

export const GATES = {
  S0: {
    needs: [],
    waivable: false,
    outputs: [
      "package.json", "pnpm-workspace.yaml", ".nvmrc", ".gitignore", "LICENSE",
      "apps/*/package.json", "packages/*/package.json",
      "scripts/check-workspace.mjs", "scripts/gate.mjs", "scripts/gate.test.mjs", "scripts/hook.test.mjs",
      "gates/gates.config.mjs", ".githooks/**", ".github/workflows/gate.yml",
    ],
    checks: [
      { id: "G-S0.1", how: "cmd", desc: "TC-S0.T1.a 워크스페이스 패키지 여섯", cmd: "node scripts/check-workspace.mjs" },
      { id: "G-S0.2", how: "test", desc: "TC-S0.T2.a 선행 미봉인 거부", cmd: nodeTest("scripts/gate.test.mjs", "TC-S0.T2.a") },
      { id: "G-S0.3", how: "test", desc: "TC-S0.T2.b 되돌리면 봉인 무효", cmd: nodeTest("scripts/gate.test.mjs", "TC-S0.T2.b") },
      { id: "G-S0.4", how: "test", desc: "TC-S0.T2.c --seal 재검", cmd: nodeTest("scripts/gate.test.mjs", "TC-S0.T2.c") },
      { id: "G-S0.5", how: "test", desc: "TC-S0.T2.d 검사 종류마다 이빨", cmd: nodeTest("scripts/gate.test.mjs", "TC-S0.T2.d") },
      { id: "G-S0.6", how: "test", desc: "TC-S0.T2.e 면제 조건", cmd: nodeTest("scripts/gate.test.mjs", "TC-S0.T2.e") },
      { id: "G-S0.7", how: "test", desc: "TC-S0.T2.f --assert-order", cmd: nodeTest("scripts/gate.test.mjs", "TC-S0.T2.f") },
      { id: "G-S0.8", how: "test", desc: "TC-S0.T3.a pre-push 훅 거부", cmd: nodeTest("scripts/hook.test.mjs", "TC-S0.T3.a") },
      { id: "G-S0.9", how: "cmd", desc: "봉인 디렉터리가 무시되지 않음", cmd: "git check-ignore -q gates/seals/S0.json", expectExit: 1 },
      { id: "G-S0.10", how: "test", desc: "TC-S0.T2.g 위조 봉인 무효", cmd: nodeTest("scripts/gate.test.mjs", "TC-S0.T2.g") },
      { id: "G-S0.11", how: "test", desc: "TC-S0.T2.h --verify-seals --rerun", cmd: nodeTest("scripts/gate.test.mjs", "TC-S0.T2.h") },
      { id: "G-S0.12", how: "test", desc: "TC-S0.T2.i 설정 변경으로 우회 불가", cmd: nodeTest("scripts/gate.test.mjs", "TC-S0.T2.i") },
      { id: "G-S0.13", how: "test", desc: "TC-S0.T2.j --head 지정", cmd: nodeTest("scripts/gate.test.mjs", "TC-S0.T2.j") },
      { id: "G-S0.14", how: "test", desc: "TC-S0.T3.b 다른 브랜치 push 거부", cmd: nodeTest("scripts/hook.test.mjs", "TC-S0.T3.b") },
      { id: "G-S0.15", how: "test", desc: "CI 테스트 명령", cmd: 'node --test --test-reporter=tap "scripts/*.test.mjs"' },
    ],
  },
  // S1 검사는 확인용 코드(spikes)로 돈다. spikes 는 S7.T2 에서 지웠으므로 main 에서 gate S1 은 돌지 않는다.
  // 봉인 커밋에서만 돈다: gate --verify-seals --rerun (봉인 커밋 작업 트리) 과 CI 의 s1-seal 잡 (ci.yml).
  S1: {
    needs: ["S0"],
    waivable: false,
    outputs: ["spikes/**", "docs/verify/**", "scripts/check-verify.mjs", "scripts/check-verify.test.mjs"],
    checks: [
      { id: "G-S1.1", how: "cmd", requires: ["local-services"], desc: "TC-S1.T1.a 최소 범위 토큰으로 관리 호출 7개", cmd: "node spikes/v10/run.mjs --assert min" },
      { id: "G-S1.2", how: "cmd", requires: ["local-services"], desc: "TC-S1.T1.b 더 낮은 범위는 실패", cmd: "node spikes/v10/run.mjs --assert lower-fails" },
      { id: "G-S1.3", how: "cmd", requires: ["local-services"], desc: "TC-S1.T2.a 끈 키 즉시 거부", cmd: "node spikes/v11/run.mjs --assert" },
      { id: "G-S1.4", how: "cmd", requires: ["local-services"], desc: "TC-S1.T3.a 허용 목록이 실제 요청을 덮음", cmd: "node spikes/v16/check.mjs covers" },
      { id: "G-S1.5", how: "cmd", desc: "TC-S1.T3.b 관리 별칭은 허용 목록 밖", cmd: "node spikes/v16/check.mjs deny" },
      { id: "G-S1.6", how: "test", requires: ["local-services"], desc: "TC-S1.T4.a input:false 권한 칼럼 보호", cmd: 'pnpm -C spikes/v17 test -t "TC-S1.T4.a"' },
      { id: "G-S1.7", how: "test", requires: ["local-services"], desc: "TC-S1.T4.b 대조군", cmd: 'pnpm -C spikes/v17 test -t "TC-S1.T4.b"' },
      { id: "G-S1.8", how: "cmd", requires: ["local-services"], desc: "TC-S1.T5.a 비밀 값 전부로 운영 모드 시작", cmd: "node spikes/v21/run.mjs all" },
      { id: "G-S1.9", how: "cmd", requires: ["local-services"], desc: "TC-S1.T5.b 각 비밀 값의 필수 여부", cmd: "node spikes/v21/run.mjs each" },
      { id: "G-S1.10", how: "test", requires: ["local-services"], desc: "TC-S1.T6.a 네 DB 가입·로그인·세션", cmd: 'pnpm -C spikes/v26 test -t "TC-S1.T6.a"' },
      { id: "G-S1.11", how: "test", requires: ["local-services"], desc: "TC-S1.T6.b resolveUser 트랜잭션 롤백", cmd: 'pnpm -C spikes/v26 test -t "TC-S1.T6.b"' },
      { id: "G-S1.12", how: "test", requires: ["local-services"], desc: "TC-S1.T6.c 대소문자 이메일 중복", cmd: 'pnpm -C spikes/v26 test -t "TC-S1.T6.c"' },
      { id: "G-S1.13", how: "cmd", requires: ["local-services"], desc: "TC-S1.T7.a Workers + MySQL", cmd: "node spikes/v27/probe.mjs" },
      { id: "G-S1.14", how: "cmd", desc: "확인 파일 7개 존재·모양", cmd: "node scripts/check-verify.mjs present" },
      { id: "G-S1.15", how: "cmd", desc: "설계를 막는 결과 없음", cmd: "node scripts/check-verify.mjs unblocked" },
      { id: "G-S1.16", how: "cmd", desc: "막았던 결과는 현재 계획서 버전을 가리킴", cmd: "node scripts/check-verify.mjs resolved" },
      { id: "G-S1.17", how: "test", desc: "TC-S1.G.a~d 확인 결과 검사기 음성 대조", cmd: "node --test --test-reporter=tap scripts/check-verify.test.mjs" },
    ],
  },
  S2: {
    needs: ["S1"],
    waivable: false,
    outputs: [
      "packages/db/package.json", "packages/db/src/**", "packages/db/scripts/**", "packages/db/migrations/**", "packages/db/test/**",
      "packages/db/*.config.ts", "scripts/schema-lint.mjs", "test/fixtures/**", "docker-compose.test.yml",
    ],
    checks: [
      { id: "G-S2.1", how: "cmd", desc: "TC-S2.T1.a 생성물이 공통 정의와 같음", cmd: "pnpm -C packages/db gen && git diff --exit-code packages/db/src/schema/" },
      { id: "G-S2.2", how: "cmd", desc: "TC-S2.T1.b 스키마 규칙 위반 0", cmd: "node scripts/schema-lint.mjs" },
      { id: "G-S2.3", how: "cmd", desc: "TC-S2.T1.c 린트 음성 대조 (픽스처 위반 8)", cmd: "node scripts/schema-lint.mjs --fixture test/fixtures/bad-schema.ts --expect 8" },
      { id: "G-S2.4", how: "test", desc: "TC-S2.T2.a 시드 기본값", cmd: 'pnpm -C packages/db test -t "TC-S2.T2.a"' },
      { id: "G-S2.5", how: "test", desc: "TC-S2.T2.b 시드가 운영자 값을 덮지 않음", cmd: 'pnpm -C packages/db test -t "TC-S2.T2.b"' },
      { id: "G-S2.6", how: "test", requires: ["local-services"], desc: "TC-S2.T3.a 다섯 DB 빈 상태 → 최신 마이그레이션", cmd: "pnpm -C packages/db test:migrate --db sqlite,mysql,mariadb,pg,d1" },
      { id: "G-S2.7", how: "cmd", desc: "TC-S2.T3.b 마이그레이션과 스키마가 같음", cmd: "pnpm -C packages/db check:drift" },
      { id: "G-S2.8", how: "test", requires: ["local-services"], desc: "TC-S2.T3.c 이메일 소문자 저장·대소문자 중복 거부", cmd: 'pnpm -C packages/db test:migrate -t "TC-S2.T3.c"' },
      { id: "G-S2.9", how: "grep", desc: "MySQL id 는 VARCHAR(36)", pattern: 'varchar\\("id", \\{ length: 36', in: ["packages/db/src/schema/mysql.ts"], op: ">=", limit: 4 },
      { id: "G-S2.10", how: "grep", desc: "지원 DB 최소 버전 고정", pattern: "mysql:8.0|mariadb:10.11|postgres:14", in: ["docker-compose.test.yml"], op: "==", limit: 3 },
      { id: "G-S2.11", how: "test", requires: ["local-services"], desc: "TC-S2.T3.e 2038 년 이후 시각 왕복", cmd: 'pnpm -C packages/db test:migrate -t "TC-S2.T3.e"' },
      { id: "G-S2.12", how: "test", requires: ["local-services"], desc: "TC-S2.T3.f 토큰·식별자 대소문자 구분", cmd: 'pnpm -C packages/db test:migrate -t "TC-S2.T3.f"' },
      { id: "G-S2.13", how: "test", requires: ["local-services"], desc: "TC-S2.T3.d 마이그레이션 DB 구조 = 스키마 DB 구조", cmd: 'pnpm -C packages/db test:migrate -t "TC-S2.T3.d"' },
    ],
  },
  S3: {
    needs: ["S2"],
    waivable: false,
    outputs: [
      "packages/auth/src/**", "packages/auth/test/**", "packages/auth/scripts/**", "packages/auth/*.config.ts",
      "scripts/check-sso-paths.mjs", "test/fixtures/sso-unguarded/**",
    ],
    checks: [
      { id: "G-S3.1", how: "test", requires: ["local-services"], desc: "TC-S3.T1.a 권한 칼럼 입력 무시 (네 DB)", cmd: 'pnpm -C packages/auth test -t "TC-S3.T1.a"' },
      { id: "G-S3.2", how: "test", requires: ["local-services"], desc: "TC-S3.T1.b 이메일 인증 전 로그인 거부 (네 DB)", cmd: 'pnpm -C packages/auth test -t "TC-S3.T1.b"' },
      { id: "G-S3.3", how: "test", desc: "TC-S3.T1.c 세션 쿠키 속성", cmd: 'pnpm -C packages/auth test -t "TC-S3.T1.c"' },
      { id: "G-S3.4", how: "cmd", desc: "TC-S3.T1.d SSO 공개 관리 경로 차단 (음성 대조 포함)", cmd: "node scripts/check-sso-paths.mjs && node scripts/check-sso-paths.mjs --fixture test/fixtures/sso-unguarded --expect-fail" },
      { id: "G-S3.5", how: "test", desc: "TC-S3.T2.a 콘솔 인증 링크로 인증 완료", cmd: 'pnpm -C packages/auth test -t "TC-S3.T2.a"' },
      { id: "G-S3.6", how: "test", requires: ["local-services"], desc: "TC-S3.T2.b SMTP 어댑터 → mailpit", cmd: "pnpm -C packages/auth test:smtp" },
      { id: "G-S3.7", how: "test", desc: "TC-S3.T2.c Resend·Cloudflare 요청과 오류 전달", cmd: 'pnpm -C packages/auth test -t "TC-S3.T2.c"' },
      { id: "G-S3.8", how: "test", desc: "TC-S3.T2.d 재설정 토큰 1회용", cmd: 'pnpm -C packages/auth test -t "TC-S3.T2.d"' },
      { id: "G-S3.9", how: "test", requires: ["local-services"], desc: "TC-S3.T3.a 같은 IP 반복 로그인 실패 → 429 (네 DB)", cmd: 'pnpm -C packages/auth test -t "TC-S3.T3.a"' },
      { id: "G-S3.10", how: "test", desc: "TC-S3.T3.b 비신뢰 출처 X-Forwarded-For 무시", cmd: 'pnpm -C packages/auth test -t "TC-S3.T3.b"' },
      { id: "G-S3.11", how: "test", desc: "TC-S3.T3.c 신뢰 프록시 뒤 클라이언트별 계산", cmd: 'pnpm -C packages/auth test -t "TC-S3.T3.c"' },
      { id: "G-S3.12", how: "json", desc: "Better Auth 버전 고정", file: "packages/auth/package.json", path: "dependencies.better-auth", op: "==", value: "1.7.7" },
      // 권한 칼럼 다섯은 packages/db 의 USER_ADDITIONAL_FIELDS 에 정의되고 auth 구성이 AUTH_SCHEMA_OPTIONS 로 그대로 쓴다.
      // 칼럼 이름과 input: false 가 한 줄에 있는 정의만 센다 (주석·TABLES 의 칼럼 정의는 걸리지 않는다).
      { id: "G-S3.13", how: "grep", desc: "권한 칼럼 다섯 input: false", pattern: "(role|status|monthlyLimitUsd|maxKeys|isBootstrapAdmin): \\{ type: [^}]*input:\\s*false", in: ["packages/db/src/schema/common.ts"], op: "==", limit: 5 },
      { id: "G-S3.14", how: "test", desc: "TC-S3.T1.e 구성과 스키마가 같은 옵션", cmd: 'pnpm -C packages/auth test -t "TC-S3.T1.e"' },
      { id: "G-S3.15", how: "test", desc: "TC-S3.T2.e 메일 전송 시간으로 계정 존재 노출 없음", cmd: 'pnpm -C packages/auth test -t "TC-S3.T2.e"' },
      { id: "G-S3.16", how: "test", desc: "TC-S3.T3.d 감싼 handler 만 내보냄", cmd: 'pnpm -C packages/auth test -t "TC-S3.T3.d"' },
      { id: "G-S3.17", how: "test", desc: "TC-S3.T1.f 짧은 secret 거부", cmd: 'pnpm -C packages/auth test -t "TC-S3.T1.f"' },
      { id: "G-S3.18", how: "test", desc: "TC-S3.T2.f 운영에서 콘솔 어댑터 거부", cmd: 'pnpm -C packages/auth test -t "TC-S3.T2.f"' },
      { id: "G-S3.19", how: "test", desc: "TC-S3.T1.d 관리 경로 404 (대조: 차단 없으면 404 아님)", cmd: 'pnpm -C packages/auth test -t "TC-S3.T1.d"' },
    ],
  },
  S4: {
    needs: ["S3"],
    waivable: false,
    outputs: [
      "packages/runtime/src/**", "packages/runtime/test/**", "packages/runtime/scripts/**", "packages/runtime/*.config.ts",
      "apps/server/src/**", "apps/server/test/**", "apps/server/scripts/**", "apps/server/*.config.ts",
      "apps/web/src/**", "apps/web/static/**", "apps/web/svelte.config.js", "apps/web/vite.config.ts",
      "tsconfig.json", "apps/*/tsconfig.json", "packages/*/tsconfig.json",
    ],
    checks: [
      { id: "G-S4.1", how: "test", requires: ["local-services"], desc: "TC-S4.T1.a job_leases 동시 임대는 하나만", cmd: 'pnpm -C packages/runtime test:db -t "TC-S4.T1.a" --db mysql,pg' },
      { id: "G-S4.2", how: "test", requires: ["local-services"], desc: "TC-S4.T1.b 만료 임대는 다른 인스턴스가", cmd: 'pnpm -C packages/runtime test:db -t "TC-S4.T1.b" --db mysql,pg' },
      { id: "G-S4.3", how: "test", desc: "TC-S4.T1.c Workers clientIp 는 CF-Connecting-IP", cmd: 'pnpm -C packages/runtime test -t "TC-S4.T1.c"' },
      { id: "G-S4.4", how: "test", desc: "TC-S4.T2.a Node ↔ Workers 암호문 교차 복호화", cmd: "pnpm -C packages/runtime test:cross-runtime" },
      { id: "G-S4.5", how: "test", desc: "TC-S4.T2.b 변조 암호문 거부", cmd: 'pnpm -C packages/runtime test -t "TC-S4.T2.b"' },
      { id: "G-S4.6", how: "test", desc: "TC-S4.T2.c 32바이트 아닌 키 거부", cmd: 'pnpm -C packages/runtime test -t "TC-S4.T2.c"' },
      { id: "G-S4.7", how: "test", desc: "TC-S4.T3.a 깊은 주소는 SPA, /api 는 JSON 404", cmd: 'pnpm -C apps/server test -t "TC-S4.T3.a"' },
      { id: "G-S4.8", how: "test", desc: "TC-S4.T3.b Node·Workers 같은 빌드 제공", cmd: 'pnpm -C apps/server test:both-runtimes -t "TC-S4.T3.b"' },
      { id: "G-S4.9", how: "cmd", desc: "TC-S4.T3.c SPA 빌드에 서버 산출 없음", cmd: "pnpm -C apps/web build && test ! -d apps/web/build/server" },
      { id: "G-S4.10", how: "test", desc: "TC-S4.T4.a 설치 토큰 1회용", cmd: 'pnpm -C apps/server test -t "TC-S4.T4.a"' },
      { id: "G-S4.11", how: "test", desc: "TC-S4.T4.b 틀린 설치 토큰 거부", cmd: 'pnpm -C apps/server test -t "TC-S4.T4.b"' },
      { id: "G-S4.12", how: "test", desc: "TC-S4.T4.c 설치 토큰 원문이 DB 에 없음", cmd: 'pnpm -C apps/server test -t "TC-S4.T4.c"' },
      { id: "G-S4.13", how: "test", desc: "TC-S4.T4.d 관리자가 있으면 토큰 없음", cmd: 'pnpm -C apps/server test -t "TC-S4.T4.d"' },
      { id: "G-S4.14", how: "grep", desc: "SPA 모드 고정", pattern: "export const ssr = false", in: ["apps/web/src/routes/+layout.ts"], op: "==", limit: 1 },
      { id: "G-S4.15", how: "test", requires: ["local-services"], desc: "TC-S4.T1.d DB 세션 시간대 UTC 강제", cmd: 'pnpm -C packages/runtime test:db -t "TC-S4.T1.d" --db mysql,mariadb,pg' },
      { id: "G-S4.16", how: "test", desc: "TC-S4.T1.e clientIp 가 null 이면 시작 거부", cmd: 'pnpm -C packages/runtime test -t "TC-S4.T1.e"' },
      { id: "G-S4.17", how: "cmd", desc: "TC-S4.T3.d 모든 패키지 타입 검사", cmd: "pnpm -r typecheck" },
      { id: "G-S4.18", how: "test", desc: "TC-S4.T2.d 다른 AAD 로 복호화 거부", cmd: 'pnpm -C packages/runtime test -t "TC-S4.T2.d"' },
      { id: "G-S4.19", how: "test", desc: "TC-S4.T3.e /api 본문 64KB 상한 (Node·Workers)", cmd: 'pnpm -C apps/server test -t "TC-S4.T3.e" && pnpm -C apps/server test:both-runtimes -t "TC-S4.T3.e"' },
      { id: "G-S4.20", how: "test", desc: "TC-S4.T3.f 보안 헤더와 SPA CSP (Node·Workers)", cmd: 'pnpm -C apps/server test:both-runtimes -t "TC-S4.T3.f"' },
      { id: "G-S4.21", how: "test", desc: "TC-S4.T4.e 설치 전 가입 403·email_taken 409", cmd: 'pnpm -C apps/server test -t "TC-S4.T4.e"' },
      { id: "G-S4.22", how: "test", requires: ["local-services"], desc: "TC-S4.T4.f 동시 설치 10건 → 관리자 하나 (SQLite·MySQL·PG)", cmd: 'pnpm -C apps/server test:db -t "TC-S4.T4.f" --db sqlite,mysql,pg' },
    ],
  },
  S5: {
    needs: ["S4"],
    waivable: false,
    outputs: [
      "packages/omniroute/src/**", "packages/omniroute/test/**", "packages/omniroute/*.config.ts",
      "tests/contract/**", "apps/server/src/setup/omniroute.ts",
      "apps/server/test/contract/**", "apps/server/vitest.contract.config.ts",
    ],
    // 계약 테스트는 tests/contract 의 OmniRoute 컨테이너(127.0.0.1:20170)를 띄우고 돈다 (tests/contract/run.mjs).
    checks: [
      { id: "G-S5.1", how: "test", requires: ["local-services"], desc: "TC-S5.T1.a 계약 환경이 0단계 실측값 재현", cmd: 'pnpm test:contract -t "TC-S5.T1.a"' },
      { id: "G-S5.2", how: "test", requires: ["local-services"], desc: "TC-S5.T2.a 키 없는 /v1 → 401", cmd: 'pnpm test:contract -t "TC-S5.T2.a"' },
      { id: "G-S5.3", how: "test", requires: ["local-services"], desc: "TC-S5.T2.b 생성 → 끄기 → 예산 → 켜기 → 요청", cmd: 'pnpm test:contract -t "TC-S5.T2.b"' },
      { id: "G-S5.4", how: "test", requires: ["local-services"], desc: "TC-S5.T2.c 끈 키 즉시 거부", cmd: 'pnpm test:contract -t "TC-S5.T2.c"' },
      { id: "G-S5.5", how: "test", requires: ["local-services"], desc: "TC-S5.T2.d 예산 초과 429 (arm64 BUDGET_EXCEEDED, amd64 예산 메시지)", cmd: 'pnpm test:contract -t "TC-S5.T2.d"' },
      { id: "G-S5.6", how: "test", requires: ["local-services"], desc: "TC-S5.T2.e 키별 분석 비용 (스트리밍 포함)", cmd: 'pnpm test:contract -t "TC-S5.T2.e"' },
      { id: "G-S5.7", how: "test", requires: ["local-services"], desc: "TC-S5.T2.f 응답 형식 변화 → 오류", cmd: 'pnpm test:contract -t "TC-S5.T2.f"' },
      { id: "G-S5.8", how: "test", requires: ["local-services"], desc: "TC-S5.T2.g 쿠키 변경 요청에 Origin", cmd: 'pnpm test:contract -t "TC-S5.T2.g"' },
      { id: "G-S5.9", how: "grep", desc: "TC-S5.T2.h 어댑터 밖 OmniRoute 관리 호출 0", pattern: "/api/(keys|usage)", in: ["apps", "packages"], exclude: ["packages/omniroute/**"], op: "==", limit: 0 },
      { id: "G-S5.10", how: "test", requires: ["local-services"], desc: "TC-S5.T3.a 설치 뒤 토큰 암호화 저장", cmd: 'pnpm test:contract -t "TC-S5.T3.a"' },
      { id: "G-S5.11", how: "test", requires: ["local-services"], desc: "TC-S5.T3.b 저장 토큰 범위 = V10 minScope", cmd: 'pnpm test:contract -t "TC-S5.T3.b"' },
      { id: "G-S5.12", how: "test", requires: ["local-services"], desc: "TC-S5.T3.c 틀린 비밀번호 → manual_required, 관리자는 생성", cmd: 'pnpm test:contract -t "TC-S5.T3.c"' },
      { id: "G-S5.13", how: "grep", desc: "OmniRoute 버전 고정 (태그 + digest)", pattern: "diegosouzapw/omniroute:3\\.8\\.51@sha256:", in: ["tests/contract/docker-compose.yml"], op: "==", limit: 1 },
      { id: "G-S5.14", how: "test", requires: ["local-services"], desc: "TC-S5.T2.i 어댑터는 키 scopes 를 보내지 않음", cmd: 'pnpm test:contract -t "TC-S5.T2.i"' },
      { id: "G-S5.15", how: "test", requires: ["local-services"], desc: "TC-S5.T3.d 토큰 붙여 넣기는 관리자·write 만", cmd: 'pnpm test:contract -t "TC-S5.T3.d"' },
      { id: "G-S5.16", how: "test", requires: ["local-services"], desc: "TC-S5.T2.j 월 예산 0 거부 (OmniRoute 0 = 무제한 대조)", cmd: 'pnpm test:contract -t "TC-S5.T2.j"' },
      { id: "G-S5.17", how: "test", requires: ["local-services"], desc: "TC-S5.T2.k 리다이렉트를 따라가지 않음", cmd: 'pnpm test:contract -t "TC-S5.T2.k"' },
      { id: "G-S5.18", how: "test", requires: ["local-services"], desc: "TC-S5.T3.e 남은 토큰 id 를 로그에", cmd: 'pnpm test:contract -t "TC-S5.T3.e"' },
      { id: "G-S5.19", how: "test", requires: ["local-services"], desc: "TC-S5.T2.l 키 id 형식 검사", cmd: 'pnpm test:contract -t "TC-S5.T2.l"' },
      { id: "G-S5.20", how: "test", requires: ["local-services"], desc: "TC-S5.T2.m 음수 비용 거부", cmd: 'pnpm test:contract -t "TC-S5.T2.m"' },
      { id: "G-S5.21", how: "test", requires: ["local-services"], desc: "TC-S5.T3.f 부트스트랩 전체 제한 시간 하나", cmd: 'pnpm test:contract -t "TC-S5.T3.f"' },
    ],
  },
  // S6 의 test:deploy·e2e 는 회원 앱 이미지를 만들고 Compose 묶음을 띄운다. workers-* E2E 는 계약 환경 OmniRoute(127.0.0.1:20170)와
  // 시험용 MySQL·Postgres(docker-compose.test.yml)를 쓴다. 메모리가 빠듯하면 조합을 하나씩 돌린다 (각 조합은 끝나면 내린다).
  S6: {
    needs: ["S5"],
    waivable: false,
    outputs: [
      "scripts/init.mjs", "scripts/init.test.mjs", ".env.example", "docker-compose.yml", "deploy/**", ".dockerignore",
      "apps/server/Dockerfile", "apps/server/wrangler.toml", "apps/server/vitest.workers.config.ts", "deploy/workers-deploy.mjs",
      "tests/e2e/**", "tests/deploy/**",
    ],
    checks: [
      { id: "G-S6.1", how: "test", desc: "TC-S6.T1.a 필수 값이 모두 들어간다", cmd: nodeTest("scripts/init.test.mjs", "TC-S6.T1.a") },
      { id: "G-S6.2", how: "test", desc: "TC-S6.T1.b 두 번 생성한 비밀 값이 서로 다르다", cmd: nodeTest("scripts/init.test.mjs", "TC-S6.T1.b") },
      { id: "G-S6.3", how: "test", desc: "TC-S6.T1.c 기존 .env 를 덮지 않는다", cmd: nodeTest("scripts/init.test.mjs", "TC-S6.T1.c") },
      { id: "G-S6.16", how: "grep", desc: "REQUIRE_API_KEY=true 명시", pattern: "REQUIRE_API_KEY=true", in: [".env.example"], op: "==", limit: 1 },
      { id: "G-S6.4", how: "test", requires: ["local-services"], desc: "TC-S6.T2.a Caddy 를 거친 키 없는 /v1 → 401", cmd: 'pnpm test:deploy -t "TC-S6.T2.a"' },
      { id: "G-S6.5", how: "test", requires: ["local-services"], desc: "TC-S6.T2.b 허용 목록 밖 /v1 → Caddy 404", cmd: 'pnpm test:deploy -t "TC-S6.T2.b"' },
      { id: "G-S6.6", how: "test", requires: ["local-services"], desc: "TC-S6.T2.c /api/* 는 회원 앱으로", cmd: 'pnpm test:deploy -t "TC-S6.T2.c"' },
      { id: "G-S6.7", how: "test", requires: ["local-services"], desc: "TC-S6.T2.d OmniRoute 포트는 루프백에만", cmd: 'pnpm test:deploy -t "TC-S6.T2.d"' },
      { id: "G-S6.9", how: "cmd", requires: ["local-services"], desc: "TC-S6.T4.a 여섯 조합 E2E: docker-sqlite", cmd: "pnpm e2e --combo docker-sqlite" },
      { id: "G-S6.10", how: "cmd", requires: ["local-services"], desc: "TC-S6.T4.b 여섯 조합 E2E: docker-mysql", cmd: "pnpm e2e --combo docker-mysql" },
      { id: "G-S6.11", how: "cmd", requires: ["local-services"], desc: "TC-S6.T4.c 여섯 조합 E2E: docker-pg", cmd: "pnpm e2e --combo docker-pg" },
      { id: "G-S6.12", how: "cmd", requires: ["local-services"], desc: "TC-S6.T4.d 여섯 조합 E2E: workers-d1", cmd: "pnpm e2e --combo workers-d1" },
      { id: "G-S6.13", how: "cmd", requires: ["local-services"], desc: "TC-S6.T4.e 여섯 조합 E2E: workers-mysql", cmd: "pnpm e2e --combo workers-mysql" },
      { id: "G-S6.14", how: "cmd", requires: ["local-services"], desc: "TC-S6.T4.f 여섯 조합 E2E: workers-pg", cmd: "pnpm e2e --combo workers-pg" },
      { id: "G-S6.15", how: "grep", desc: "Compose OmniRoute 버전 고정 (태그 + digest)", pattern: "diegosouzapw/omniroute:3\\.8\\.51@sha256:", in: ["docker-compose.yml"], op: "==", limit: 1 },
      { id: "G-S6.17", how: "grep", desc: "DB 최소 버전", pattern: "mysql:8.0|postgres:14", in: ["docker-compose.yml"], op: "==", limit: 2 },
      { id: "G-S6.18", how: "grep", desc: "대시보드 포트 루프백 고정", pattern: '"127\\.0\\.0\\.1:20128:20128"', in: ["docker-compose.yml"], op: "==", limit: 1 },
      { id: "G-S6.19", how: "test", requires: ["local-services"], desc: "TC-S6.T2.e Caddy 뒤 클라이언트별 계산·비신뢰 XFF 경고", cmd: 'pnpm test:deploy -t "TC-S6.T2.e"' },
      { id: "G-S6.20", how: "test", requires: ["local-services"], desc: "TC-S6.T2.f 빈 DB 에 마이그레이션 먼저 (세 프로필)", cmd: 'pnpm test:deploy -t "TC-S6.T2.f"' },
      { id: "G-S6.8", how: "cmd", requires: ["local-services"], desc: "TC-S6.T3.a 세 환경 번들 (wrangler deploy --dry-run)", cmd: "pnpm -C apps/server dry-run:all" },
      { id: "G-S6.21", how: "test", requires: ["local-services"], desc: "TC-S6.T3.b Workers 설치 토큰 되살리기 (wrangler dev + MySQL·PG 동시 경쟁)", cmd: 'pnpm -C apps/server test:workers -t "TC-S6.T3.b" && pnpm -C apps/server test:db -t "TC-S6.T3.b" --db mysql,pg' },
      { id: "G-S6.22", how: "test", requires: ["local-services"], desc: "TC-S6.T3.c DB 시간대와 무관한 created_at (스키마 린트 R6 + 세션 시간대 비강제 연결)", cmd: 'node scripts/schema-lint.mjs && pnpm -C packages/runtime test:db -t "TC-S6.T3.c" --db mysql,mariadb,pg' },
      { id: "G-S6.23", how: "test", requires: ["local-services"], desc: "TC-S6.T3.d Workers 배포 전 마이그레이션", cmd: 'pnpm -C apps/server test:workers -t "TC-S6.T3.d"' },
      { id: "G-S6.24", how: "grep", desc: "설치 운영 안내 (한 인스턴스)", pattern: "한 인스턴스", in: ["deploy/README.md"], op: ">=", limit: 1 },
      { id: "G-S6.25", how: "grep", desc: "Compose 신뢰 프록시 기본값", pattern: "TRUSTED_PROXIES", in: ["docker-compose.yml"], op: ">=", limit: 1 },
      { id: "G-S6.26", how: "test", desc: "TC-S6.T1.d OmniRoute 비밀번호는 .env.setup 에만", cmd: nodeTest("scripts/init.test.mjs", "TC-S6.T1.d") },
      { id: "G-S6.27", how: "test", requires: ["local-services"], desc: "TC-S6.T2.g 설치 뒤 남은 OmniRoute 비밀번호 경고 (Compose·Workers)", cmd: 'pnpm test:deploy -t "TC-S6.T2.g" && pnpm -C apps/server test:workers -t "TC-S6.T2.g"' },
      { id: "G-S6.28", how: "test", requires: ["local-services"], desc: "TC-S6.T3.e 약한 SETUP_TOKEN 거부 (Node·Workers)", cmd: 'pnpm -C apps/server test -t "TC-S6.T3.e" && pnpm -C apps/server test:workers -t "TC-S6.T3.e"' },
      { id: "G-S6.29", how: "test", requires: ["local-services"], desc: "TC-S6.T3.f 설치 시도 횟수 제한 → 429 (Node·Workers)", cmd: 'pnpm -C apps/server test -t "TC-S6.T3.f" && pnpm -C apps/server test:workers -t "TC-S6.T3.f"' },
      { id: "G-S6.30", how: "grep", desc: "OmniRoute 비공개 안내 (20128·/api 비공개, Workers 는 Tunnel·Access 로만)", pattern: "OmniRoute 20128 포트와 /api/\\* 는 공개로 열지 않는다|Workers 조합은 Cloudflare Tunnel·Access 로만 연결한다", in: ["deploy/README.md"], op: "==", limit: 2 },
    ],
  },
  // S7 의 CI 매트릭스(.github/workflows/ci.yml)가 S2~S6 게이트를 서비스를 띄운 잡에서 그대로 돈다 (requires 로 건너뛰지 않는다).
  S7: {
    needs: ["S6"],
    waivable: false,
    outputs: [
      ".github/workflows/ci.yml", "scripts/check-ci-matrix.mjs", "test/fixtures/ci-5combos.yml", "test/fixtures/ci-guard/**", "scripts/gate.mjs", "scripts/gate.test.mjs",
      "docker-compose.yml", ".env.example", "deploy/README.md", "tests/deploy/deploy.test.mjs", "apps/server/test/workers.test.ts",
    ],
    checks: [
      { id: "G-S7.1", how: "cmd", desc: "TC-S7.T1.a·b·c CI 매트릭스 여섯 조합·명령이 조용히 빠지지 않음 (음성 대조 포함)", cmd: "node scripts/check-ci-matrix.mjs --expect 6 && node scripts/check-ci-matrix.mjs --fixture test/fixtures/ci-5combos.yml --expect 6 --expect-fail && node scripts/check-ci-matrix.mjs --fixture-dir test/fixtures/ci-guard --expect 6 --expect-fail" },
      // grep 종료코드 1(일치 없음)만 통과다. 경로가 없어 grep 이 2 로 끝나면 실패한다
      { id: "G-S7.2", how: "cmd", desc: "TC-S7.T2.a 확인용 코드가 남지 않음", cmd: 'test ! -e spikes && { grep -rn --exclude-dir=node_modules --exclude-dir=build --exclude-dir=.svelte-kit --exclude-dir=.wrangler "spikes/" apps packages scripts tests; test $? -eq 1; }' },
      // 꺼진 테스트와 미구현 표식: vitest·node:test 의 .only·.skip·.skipIf·.todo·.skip.each·.only.each·runIf·x접두,
      // node:test 옵션 { skip: true }·{ todo: true }, TODO·FIXME·"not implemented". 빌드 산출(build·.svelte-kit·.wrangler·dist)은 보지 않는다
      // (node_modules 는 원래 안 본다). 제외는 하나: scripts/gate.test.mjs 는 gate 의 test 판정 음성 대조(TC-S0.T2.d)로
      // { skip: true }·{ todo: true } 테스트 파일을 문자열로 만들어 "꺼진 테스트만 있으면 실패" 를 확인한다
      { id: "G-S7.3", how: "grep", desc: "TC-S7.T3.a 건너뛴 테스트와 미구현 표식 0", pattern: "\\.(only|skip|skipIf|todo)\\(|\\.(skip|only)\\.|runIf\\(|\\b(skip|todo)\\s*:\\s*true|\\b(xit|xdescribe|xtest)\\(|TODO|FIXME|not implemented", in: ["apps", "packages", "tests", "scripts"], exclude: ["apps/web/build/**", "**/.svelte-kit/**", "**/.wrangler/**", "**/dist/**", "scripts/gate.test.mjs"], op: "==", limit: 0 },
      // S0~S6 봉인이 모두 유효(✅)하다. 하나라도 ⚠·🔓·🔒 면 실패
      { id: "G-S7.4", how: "cmd", desc: "앞 단계 봉인 모두 유효", cmd: `node -e 'const r=JSON.parse(require("child_process").execFileSync(process.execPath,["scripts/gate.mjs","--status","--json"],{encoding:"utf8"}));const want=["S0","S1","S2","S3","S4","S5","S6"];const bad=want.filter(p=>r.find(x=>x.phase===p)?.state!=="sealed");if(bad.length){console.error("봉인 무효·없음: "+bad.join(", "));process.exit(1)}console.log("S0~S6 봉인 유효")'` },
      { id: "G-S7.5", how: "cmd", desc: "처음 커밋부터 순서 위반 없음", cmd: 'node scripts/gate.mjs --assert-order --base "$(git rev-list --max-parents=0 HEAD)"' },
      { id: "G-S7.6", how: "test", requires: ["local-services"], desc: "TC-S7.T4.a Workers 에서 OmniRoute 3xx 를 따라가지 않음", cmd: 'pnpm -C apps/server test:workers -t "TC-S7.T4.a"' },
      { id: "G-S7.7", how: "test", requires: ["local-services"], desc: "TC-S7.T5.a 덧씌우기 없는 Compose 가 최상위 .env.setup 을 app 에 넘김", cmd: 'pnpm test:deploy -t "TC-S7.T5.a"' },
      { id: "G-S7.8", how: "test", requires: ["local-services"], desc: "TC-S7.T6.a·b app 은 Caddy 고정 주소 하나만 신뢰 (S6 보안 리뷰 L3)", cmd: 'pnpm test:deploy -t "TC-S7.T6"' },
      { id: "G-S7.9", how: "test", desc: "TC-S0.T2.n 봉인 재검이 설치 실패를 보고 (S7 리뷰 M4)", cmd: nodeTest("scripts/gate.test.mjs", "TC-S0.T2.n") },
    ],
  },

  // ---------- 2단계 "키·한도" (실행판 docs/plan/phase2-todo.md) ----------
  // K0~K6 은 직렬이다. strictTests: test 검사마다 expectPassed(통과 수 ==)가 있어야 한다 (K0.T1 이 gate 에 넣는다).
  // outputs 는 그 단계가 새로 만드는, 이력에서 한 번도 바뀐 적 없는 경로만 둔다. --assert-order 를 처음 커밋부터 도는 검사
  // (ci.yml order 잡, G-S7.5, 새 브랜치 push 의 gate.yml)는 지금 설정의 잠긴 단계 outputs 로 이력 전체를 본다. 1단계가 고친 파일
  // (lease.ts·schema·migrations·omniroute/src 등)을 잠긴 단계 outputs 에 넣으면 그 단계가 열릴 때까지 CI 가 빨갛다.
  // 고칠 기존 파일은 어느 단계 outputs 에도 넣지 않는다 (앞 단계 봉인이 R1 으로 순서를 지킨다).
  // K1~K6 의 checks 는 그 단계를 시작할 때 실행판 GATE 표대로 채운다 (빈 단계는 gate 가 실행·봉인을 거부한다).
  K0: {
    needs: ["S7"],
    waivable: false,
    strictTests: true,
    outputs: [
      "scripts/check-ci-matrix.mjs", "test/check-ci-matrix.test.mjs", "test/fixtures/ci-guard/concurrency-cancel-main.yml",
      "scripts/check-verify.mjs", "scripts/check-verify.test.mjs",
      "scripts/check-required-checks.mjs", "test/check-required-checks.test.mjs", "test/fixtures/required-checks/**",
      "docs/verify/V12.json", "docs/verify/V13.json", "docs/verify/V15.json", "docs/verify/V18.json", "docs/verify/V19.json", "docs/verify/V20.json",
      "packages/omniroute/test/contract/verify/**", "tests/contract/budget-block.mjs", "tests/contract/budget-block.test.mjs", "tests/bench/**",
      "scripts/check-red.mjs", "test/check-red.test.mjs",
    ],
    checks: [
      // 장치 음성 대조 다시 돌리기 (1단계 TC-S0.T2.a~d, TC-S0.T3)
      { id: "G-K0.1", how: "test", desc: "TC-S0.T2.a 선행 미봉인 거부", cmd: nodeTest("scripts/gate.test.mjs", "TC-S0.T2.a"), expectPassed: 1 },
      { id: "G-K0.2", how: "test", desc: "TC-S0.T2.b 되돌리면 봉인 무효", cmd: nodeTest("scripts/gate.test.mjs", "TC-S0.T2.b"), expectPassed: 1 },
      { id: "G-K0.3", how: "test", desc: "TC-S0.T2.c --seal 재검", cmd: nodeTest("scripts/gate.test.mjs", "TC-S0.T2.c"), expectPassed: 1 },
      { id: "G-K0.4", how: "test", desc: "TC-S0.T2.d 검사 종류마다 이빨 (하위 테스트 포함 13)", cmd: nodeTest("scripts/gate.test.mjs", "TC-S0.T2.d"), expectPassed: 13 },
      { id: "G-K0.5", how: "test", desc: "TC-S0.T3 pre-push 훅 거부", cmd: nodeTest("scripts/hook.test.mjs", "TC-S0.T3"), expectPassed: 2 },
      // K0.T1 gate test 판정 expectPassed
      { id: "G-K0.6", how: "test", desc: "TC-K0.T1.a 통과 수가 expectPassed 와 다르면 실패", cmd: nodeTest("scripts/gate.test.mjs", "TC-K0.T1.a"), expectPassed: 1 },
      { id: "G-K0.7", how: "test", desc: "TC-K0.T1.b 여러 vitest 요약을 합산", cmd: nodeTest("scripts/gate.test.mjs", "TC-K0.T1.b"), expectPassed: 1 },
      { id: "G-K0.8", how: "test", desc: "TC-K0.T1.c strictTests 단계의 expectPassed 없는 test 검사 실패", cmd: nodeTest("scripts/gate.test.mjs", "TC-K0.T1.c"), expectPassed: 1 },
      { id: "G-K0.9", how: "test", desc: "TC-K0.T1.d expectPassed 없는 1단계 검사는 통과 ≥ 1 그대로", cmd: nodeTest("scripts/gate.test.mjs", "TC-K0.T1.d"), expectPassed: 1 },
      { id: "G-K0.37", how: "test", desc: "TC-K0.T1.e grep 검사의 ^·$ 는 줄 단위", cmd: nodeTest("scripts/gate.test.mjs", "TC-K0.T1.e"), expectPassed: 1 },
      // K0.T2 봉인된 단계만 CI 단계 잡 요구
      { id: "G-K0.10", how: "test", desc: "TC-K0.T2.a·b 봉인된 단계만 단계 잡 요구 (음성 대조 포함)", cmd: "node --test --test-reporter=tap test/check-ci-matrix.test.mjs", expectPassed: 2 },
      // K0.T3 main 에서 앞 실행을 취소하지 않음 (S7 리뷰 L5)
      { id: "G-K0.11", how: "cmd", desc: "TC-K0.T3.a·b concurrency 규칙 (음성 대조 포함)", cmd: "node scripts/check-ci-matrix.mjs --expect 6 && node scripts/check-ci-matrix.mjs --fixture test/fixtures/ci-guard/concurrency-cancel-main.yml --expect 6 --expect-fail" },
      // K0.T4 확인 결과 검사기 항목 묶음
      { id: "G-K0.12", how: "test", desc: "TC-K0.T4.a~e check-verify --set 음성 대조", cmd: nodeTest("scripts/check-verify.test.mjs", "TC-K0.T4"), expectPassed: 5 },
      { id: "G-K0.13", how: "cmd", desc: "확인 파일 7개 존재·모양 (V28 은 K3 리뷰)", cmd: "node scripts/check-verify.mjs present --set phase2" },
      { id: "G-K0.14", how: "cmd", desc: "설계를 막는 결과 없음", cmd: "node scripts/check-verify.mjs unblocked --set phase2" },
      { id: "G-K0.15", how: "cmd", desc: "막았던 결과는 현재 계획서 버전을 가리킴", cmd: "node scripts/check-verify.mjs resolved --set phase2" },
      // K0.T5~T10 확인 항목 (계약 환경 127.0.0.1:20170 에서 관찰 == V<n>.json answer)
      { id: "G-K0.16", how: "test", requires: ["local-services"], desc: "TC-K0.T5.a V12 키 그룹·쿼터 풀 공동 예산", cmd: 'pnpm test:contract -t "TC-K0.T5.a"', expectPassed: 1 },
      { id: "G-K0.17", how: "test", requires: ["local-services"], desc: "TC-K0.T6.a V13 call-logs 키 거르기", cmd: 'pnpm test:contract -t "TC-K0.T6.a"', expectPassed: 1 },
      { id: "G-K0.18", how: "cmd", requires: ["local-services"], desc: "TC-K0.T7.a V15 분석 API 측정 재현 (오늘 창 p95 ≤ 2,000ms·회원 ≤ 1,000ms·대조 ≤ 55,000ms, 계획서 v5.7)", cmd: "node tests/bench/analytics.mjs --assert" },
      { id: "G-K0.19", how: "json", desc: "V15 기록 수 ≥ 300,000", file: "docs/verify/V15.json", path: "answer.dataset.records", op: ">=", value: 300000 },
      { id: "G-K0.20", how: "json", desc: "V15 키 수 ≥ 300", file: "docs/verify/V15.json", path: "answer.dataset.keys", op: ">=", value: 300 },
      { id: "G-K0.21", how: "json", desc: "V15 오늘 창 분석 p95 ≤ 2,000ms (계획서 v5.7 5.3)", file: "docs/verify/V15.json", path: "answer.todayWindow.p95Ms", op: "<=", value: 2000 },
      { id: "G-K0.22", how: "json", desc: "V15 회원 하나 분석 p95 ≤ 1,000ms", file: "docs/verify/V15.json", path: "answer.member.p95Ms", op: "<=", value: 1000 },
      { id: "G-K0.23", how: "json", desc: "V15 측정 횟수 ≥ 10", file: "docs/verify/V15.json", path: "answer.todayWindow.runs", op: ">=", value: 10 },
      { id: "G-K0.39", how: "json", desc: "V15 하루 한 번 대조(지난 29일) p95 ≤ 55,000ms (1분 작업 임대)", file: "docs/verify/V15.json", path: "answer.reconcile.p95Ms", op: "<=", value: 55000 },
      { id: "G-K0.24", how: "test", requires: ["local-services"], desc: "TC-K0.T8.a V18 삭제한 키 기록이 분석에 남음", cmd: 'pnpm test:contract -t "TC-K0.T8.a"', expectPassed: 1 },
      { id: "G-K0.25", how: "test", requires: ["local-services"], desc: "TC-K0.T9.a V19 regenerate 의 id·누적 지출·예산", cmd: 'pnpm test:contract -t "TC-K0.T9.a"', expectPassed: 1 },
      { id: "G-K0.26", how: "test", requires: ["local-services"], desc: "TC-K0.T10.a·b·c V20 월 예산 시간대·달 중간 변경·경계값", cmd: 'pnpm test:contract -t "TC-K0.T10"', expectPassed: 3 },
      // K0.T11 예산 차단 판정 도우미 (amd64·arm64 빌드 차이)
      { id: "G-K0.27", how: "test", desc: "TC-K0.T11.a 두 빌드의 예산 차단은 참, 일반 429 는 거짓", cmd: nodeTest("tests/contract/budget-block.test.mjs", "TC-K0.T11.a"), expectPassed: 1 },
      // K0.T12 계획서 개정 (설계 공백 Q1~Q6)
      { id: "G-K0.28", how: "grep", desc: "TC-K0.T12.a 계획서 v5.6 변경 이력이 공백 Q1~Q6 을 닫음", pattern: "^- v5\\.6: .*Q1.*Q2.*Q3.*Q4.*Q5.*Q6", in: ["docs/design/omniroute-member-layer.md"], op: "==", limit: 1 },
      { id: "G-K0.29", how: "grep", desc: "계획서 상태 줄이 v5.6 이상", pattern: "^상태: 초안 v5\\.([6-9]|[1-9][0-9])", in: ["docs/design/omniroute-member-layer.md"], op: "==", limit: 1 },
      // K0.T13 필수 검사·병합 방식 대조
      { id: "G-K0.30", how: "test", desc: "TC-K0.T13.a·b 필수 검사 대조기 음성 대조", cmd: "node --test --test-reporter=tap test/check-required-checks.test.mjs", expectPassed: 2 },
      { id: "G-K0.31", how: "cmd", desc: "TC-K0.T13.c·TC-K0.T15.b ruleset 필수 검사 ⊇ ci.yml 잡 이름, 병합은 머지 커밋만", cmd: "node scripts/check-required-checks.mjs --repo henryj-dev/magnetosphere" },
      // K0.T14 재현 빨강 확인 장치와 이 단계의 행동 변경 재현
      { id: "G-K0.34", how: "test", desc: "TC-K0.T14.a·b·c 재현 빨강 확인기 음성 대조", cmd: "node --test --test-reporter=tap test/check-red.test.mjs", expectPassed: 3 },
      { id: "G-K0.35", how: "cmd", desc: "재현 빨강: TC-K0.T1.a 는 Red 커밋에서 실패", cmd: "node scripts/check-red.mjs --check G-K0.6 --since seal:S7" },
      { id: "G-K0.36", how: "cmd", desc: "재현 빨강: TC-K0.T3.a 는 Red 커밋에서 실패", cmd: "node scripts/check-red.mjs --check G-K0.11 --since seal:S7" },
      { id: "G-K0.38", how: "cmd", desc: "재현 빨강: TC-K0.T1.e 는 Red 커밋에서 실패", cmd: "node scripts/check-red.mjs --check G-K0.37 --since seal:S7" },
      // 이 단계의 CI 잡과 스크립트 테스트 전부
      { id: "G-K0.32", how: "grep", desc: "TC-K0.T15.a CI 단계 잡 (K0)", pattern: "^\\s+run: node scripts/gate\\.mjs K0\\b", in: [".github/workflows/ci.yml"], op: "==", limit: 1 },
      { id: "G-K0.33", how: "cmd", desc: "스크립트 테스트 전부", cmd: 'node --test --test-reporter=tap "scripts/*.test.mjs"' },
    ],
  },
  K1: {
    needs: ["K0"],
    waivable: false,
    strictTests: true,
    outputs: ["packages/db/migrations/*/0001_*", "packages/runtime/test/lease-fence/**", "apps/server/src/queue/**", "apps/server/test/queue/**"],
    checks: [
      // K1.T1 job_leases.fence·omniroute_jobs.failed_at
      { id: "G-K1.1", how: "test", requires: ["local-services"], desc: "TC-K1.T1.a 다섯 DB fence·last_slot·failed_at·key_id 칼럼 (0000 → 기존 행 → 0001)", cmd: 'pnpm -C packages/db test:migrate -t "TC-K1.T1.a" --db sqlite,mysql,mariadb,pg,d1', expectPassed: 5 },
      { id: "G-K1.2", how: "cmd", desc: "TC-K1.T1.b 생성물·드리프트", cmd: "pnpm -C packages/db gen && git diff --exit-code packages/db/src/schema/ && pnpm -C packages/db check:drift" },
      // K1.T2 임대 하트비트·펜싱 (S4 보안 리뷰 L4)
      { id: "G-K1.3", how: "test", requires: ["local-services"], desc: "TC-K1.T2.a 하트비트가 있는 동안 다른 인스턴스는 임대를 못 잡는다", cmd: 'pnpm -C packages/runtime test:db -t "TC-K1.T2.a" --db sqlite,mysql,mariadb,pg', expectPassed: 4 },
      { id: "G-K1.4", how: "test", requires: ["local-services"], desc: "TC-K1.T2.b 임대를 잃은 쪽의 펜싱 쓰기는 0행", cmd: 'pnpm -C packages/runtime test:db -t "TC-K1.T2.b" --db sqlite,mysql,mariadb,pg', expectPassed: 4 },
      { id: "G-K1.5", how: "test", desc: "TC-K1.T2.c 하트비트 실패면 작업 신호가 끊기고 호출이 멈춘다", cmd: 'pnpm -C packages/runtime test -t "TC-K1.T2.c"', expectPassed: 1 },
      { id: "G-K1.6", how: "test", requires: ["local-services"], desc: "TC-K1.T2.d fence 는 같은 이름에서 엄격히 증가", cmd: 'pnpm -C packages/runtime test:db -t "TC-K1.T2.d" --db sqlite,mysql,mariadb,pg', expectPassed: 4 },
      // K1.T3 작업 큐와 재시도 (계획서 v5.6 Q2·Q3·Q6)
      { id: "G-K1.7", how: "test", desc: "TC-K1.T3.a 재시도 간격 60,000·120,000·600,000·1,800,000ms, tick 지연 0~20초에도 0·1·3·13·43분 경계", cmd: 'pnpm -C apps/server test -t "TC-K1.T3.a"', expectPassed: 1 },
      { id: "G-K1.8", how: "test", desc: "TC-K1.T3.b 재시도 소진 → failed_at·sync_state failed·alert.job_failed", cmd: 'pnpm -C apps/server test -t "TC-K1.T3.b"', expectPassed: 1 },
      { id: "G-K1.9", how: "test", requires: ["local-services"], desc: "TC-K1.T3.c 동시 실행기 둘, 작업마다 핸들러 한 번", cmd: 'pnpm -C apps/server test:db -t "TC-K1.T3.c" --db sqlite,mysql,mariadb,pg', expectPassed: 4 },
      { id: "G-K1.10", how: "test", desc: "TC-K1.T3.d 완료 기록", cmd: 'pnpm -C apps/server test -t "TC-K1.T3.d"', expectPassed: 1 },
      { id: "G-K1.11", how: "test", desc: "TC-K1.T3.e last_error 에 비밀 값 없음", cmd: 'pnpm -C apps/server test -t "TC-K1.T3.e"', expectPassed: 1 },
      // K1.T4 주기 작업 등록
      { id: "G-K1.12", how: "test", desc: "TC-K1.T4.a 큐 실행기 1분 주기 등록", cmd: 'pnpm -C apps/server test -t "TC-K1.T4.a"', expectPassed: 1 },
      { id: "G-K1.13", how: "test", desc: "TC-K1.T4.b wrangler crons 집합 == JOBS cron 집합", cmd: 'pnpm -C apps/server test -t "TC-K1.T4.b"', expectPassed: 1 },
      { id: "G-K1.14", how: "test", requires: ["local-services"], desc: "TC-K1.T4.c Workers scheduled 는 받은 cron 의 작업만", cmd: 'pnpm -C apps/server test:workers -t "TC-K1.T4.c"', expectPassed: 1 },
      { id: "G-K1.15", how: "test", requires: ["local-services"], desc: "TC-K1.T4.d Node 는 1분 경계마다 하나만", cmd: 'pnpm -C apps/server test:db -t "TC-K1.T4.d" --db mysql,pg', expectPassed: 2 },
      { id: "G-K1.16", how: "grep", desc: "큐 실행기 등록", pattern: 'name: "omniroute_jobs"', in: ["apps/server/src/jobs.ts"], op: "==", limit: 1 },
      { id: "G-K1.17", how: "grep", desc: "재시도 간격 상수", pattern: "\\[60_000, 120_000, 600_000, 1_800_000\\]", in: ["apps/server/src/queue"], op: "==", limit: 1 },
      { id: "G-K1.18", how: "cmd", desc: "재현 빨강: TC-K1.T2.a 는 Red 커밋에서 실패", cmd: "node scripts/check-red.mjs --check G-K1.3 --since seal:K0" },
      { id: "G-K1.19", how: "cmd", desc: "타입 검사", cmd: "pnpm -r typecheck" },
      // K1.T5 CI 단계 잡과 ruleset 필수 검사
      { id: "G-K1.20", how: "grep", desc: "TC-K1.T5.a CI 단계 잡 (K1)", pattern: "^\\s+run: node scripts/gate\\.mjs K1\\b", in: [".github/workflows/ci.yml"], op: "==", limit: 1 },
      { id: "G-K1.21", how: "cmd", desc: "TC-K1.T5.b ruleset 필수 검사 ⊇ ci.yml 잡 이름, 병합은 머지 커밋만", cmd: "node scripts/check-required-checks.mjs --repo henryj-dev/magnetosphere" },
      // K1 리뷰 고침 (#1~#8, #10)
      { id: "G-K1.22", how: "test", desc: "TC-K1.T1.c 구조 비교 정규화는 문자열 리터럴 밖에서만", cmd: 'pnpm -C packages/db test -t "TC-K1.T1.c"', expectPassed: 1 },
      { id: "G-K1.23", how: "test", desc: "TC-K1.T2.e DB 응답이 멈춰도 ttl 안에 작업 신호가 끊긴다", cmd: 'pnpm -C packages/runtime test -t "TC-K1.T2.e"', expectPassed: 1 },
      { id: "G-K1.24", how: "test", requires: ["local-services"], desc: "TC-K1.T2.f 주기 경계 하나는 한 번만 돈다", cmd: 'pnpm -C packages/runtime test:db -t "TC-K1.T2.f" --db sqlite,mysql,mariadb,pg', expectPassed: 4 },
      { id: "G-K1.25", how: "test", requires: ["local-services"], desc: "TC-K1.T3.f 오래된 켜기 재시도가 새 끄기를 덮지 않는다", cmd: 'pnpm -C apps/server test:db -t "TC-K1.T3.f" --db sqlite,mysql,mariadb,pg', expectPassed: 4 },
      { id: "G-K1.26", how: "test", requires: ["local-services"], desc: "TC-K1.T3.g 실패 표시·키 sync_state·알림은 함께 남거나 함께 되돌려진다", cmd: 'pnpm -C apps/server test:db -t "TC-K1.T3.g" --db sqlite,mysql,mariadb,pg', expectPassed: 4 },
      { id: "G-K1.27", how: "test", desc: "TC-K1.T3.h 망가진 payload 는 곧바로 failed, 큐는 계속", cmd: 'pnpm -C apps/server test -t "TC-K1.T3.h"', expectPassed: 1 },
      { id: "G-K1.28", how: "test", desc: "TC-K1.T3.i 임대를 잃어 끊긴 시도는 재시도 횟수를 쓰지 않는다", cmd: 'pnpm -C apps/server test -t "TC-K1.T3.i"', expectPassed: 1 },
      { id: "G-K1.29", how: "cmd", desc: "재현 빨강: TC-K1.T3.a(개정) 는 Red 커밋에서 실패", cmd: "node scripts/check-red.mjs --check G-K1.7 --since seal:K0" },
      { id: "G-K1.30", how: "cmd", desc: "재현 빨강: TC-K1.T2.e 는 Red 커밋에서 실패", cmd: "node scripts/check-red.mjs --check G-K1.23 --since seal:K0" },
      { id: "G-K1.31", how: "cmd", desc: "재현 빨강: TC-K1.T2.f 는 Red 커밋에서 실패", cmd: "node scripts/check-red.mjs --check G-K1.24 --since seal:K0" },
      { id: "G-K1.32", how: "cmd", desc: "재현 빨강: TC-K1.T3.f 는 Red 커밋에서 실패", cmd: "node scripts/check-red.mjs --check G-K1.25 --since seal:K0" },
      { id: "G-K1.33", how: "cmd", desc: "재현 빨강: TC-K1.T3.g 는 Red 커밋에서 실패", cmd: "node scripts/check-red.mjs --check G-K1.26 --since seal:K0" },
      { id: "G-K1.34", how: "cmd", desc: "재현 빨강: TC-K1.T3.h 는 Red 커밋에서 실패", cmd: "node scripts/check-red.mjs --check G-K1.27 --since seal:K0" },
      { id: "G-K1.35", how: "cmd", desc: "재현 빨강: TC-K1.T3.i 는 Red 커밋에서 실패", cmd: "node scripts/check-red.mjs --check G-K1.28 --since seal:K0" },
      { id: "G-K1.36", how: "cmd", desc: "재현 빨강: TC-K1.T1.c 는 Red 커밋에서 실패", cmd: "node scripts/check-red.mjs --check G-K1.22 --since seal:K0" },
      // K1 재검토 고침
      { id: "G-K1.37", how: "test", requires: ["local-services"], desc: "TC-K1.T3.j 실행 중인 반영 작업에 합쳐진 끄기도 키를 끈다", cmd: 'pnpm -C apps/server test:db -t "TC-K1.T3.j" --db sqlite,mysql,mariadb,pg', expectPassed: 4 },
      { id: "G-K1.38", how: "test", requires: ["local-services"], desc: "TC-K1.T3.k 재시도 대기 중인 작업에 합쳐지면 바로 돌고 시도를 새로 센다", cmd: 'pnpm -C apps/server test:db -t "TC-K1.T3.k" --db sqlite,mysql,mariadb,pg', expectPassed: 4 },
      { id: "G-K1.39", how: "test", desc: "TC-K1.T3.l 실패 처리만 남은 작업은 핸들러를 다시 부르지 않고 경보", cmd: 'pnpm -C apps/server test -t "TC-K1.T3.l"', expectPassed: 1 },
      { id: "G-K1.40", how: "test", requires: ["local-services"], desc: "TC-K1.T3.m 매번 임대를 잃는 작업은 5번 끊긴 뒤 failed", cmd: 'pnpm -C apps/server test:db -t "TC-K1.T3.m" --db sqlite,mysql,mariadb,pg', expectPassed: 4 },
      { id: "G-K1.41", how: "test", desc: "TC-K1.T3.n key.* 작업은 keyId 필수", cmd: 'pnpm -C apps/server test -t "TC-K1.T3.n"', expectPassed: 1 },
      { id: "G-K1.42", how: "test", desc: "TC-K1.T3.o 핸들러 표 밖의 action 은 프로토타입 함수로 돌지 않는다", cmd: 'pnpm -C apps/server test -t "TC-K1.T3.o"', expectPassed: 1 },
      { id: "G-K1.43", how: "cmd", desc: "재현 빨강: TC-K1.T3.j 는 Red 커밋에서 실패", cmd: "node scripts/check-red.mjs --check G-K1.37 --since seal:K0" },
      { id: "G-K1.44", how: "cmd", desc: "재현 빨강: TC-K1.T3.k 는 Red 커밋에서 실패", cmd: "node scripts/check-red.mjs --check G-K1.38 --since seal:K0" },
      { id: "G-K1.45", how: "cmd", desc: "재현 빨강: TC-K1.T3.l 은 Red 커밋에서 실패", cmd: "node scripts/check-red.mjs --check G-K1.39 --since seal:K0" },
      { id: "G-K1.46", how: "cmd", desc: "재현 빨강: TC-K1.T3.m 은 Red 커밋에서 실패", cmd: "node scripts/check-red.mjs --check G-K1.40 --since seal:K0" },
      { id: "G-K1.47", how: "cmd", desc: "재현 빨강: TC-K1.T3.n 은 Red 커밋에서 실패", cmd: "node scripts/check-red.mjs --check G-K1.41 --since seal:K0" },
      { id: "G-K1.48", how: "cmd", desc: "재현 빨강: TC-K1.T3.o 는 Red 커밋에서 실패", cmd: "node scripts/check-red.mjs --check G-K1.42 --since seal:K0" },
    ],
  },
  K2: {
    needs: ["K1"],
    waivable: false,
    strictTests: true,
    outputs: ["apps/server/src/limits/**", "apps/server/test/limits/**", "apps/server/test/contract/limits/**"],
    checks: [
      // K2.T1 남은 한도 계산 (순수 함수)
      { id: "G-K2.1", how: "test", desc: "TC-K2.T1.a 계산식이 계획서 5.3 과 같다", cmd: 'pnpm -C apps/server test -t "TC-K2.T1.a"', expectPassed: 1 },
      { id: "G-K2.2", how: "test", desc: "TC-K2.T1.b 한도를 넘긴 회원은 남은 0·끄기 (Q1)", cmd: 'pnpm -C apps/server test -t "TC-K2.T1.b"', expectPassed: 1 },
      { id: "G-K2.3", how: "test", desc: "TC-K2.T1.c 한도 NULL 은 예산 없음", cmd: 'pnpm -C apps/server test -t "TC-K2.T1.c"', expectPassed: 1 },
      { id: "G-K2.4", how: "test", desc: "TC-K2.T1.d 남은 0·사용액 0 키는 끄기 대상 (Q1)", cmd: 'pnpm -C apps/server test -t "TC-K2.T1.d"', expectPassed: 1 },
      { id: "G-K2.5", how: "test", desc: "TC-K2.T1.e 부동소수 오차로 남은 한도가 생기지 않음", cmd: 'pnpm -C apps/server test -t "TC-K2.T1.e"', expectPassed: 1 },
      // K2.T2 달 경계와 시간대 (V20 UTC, Q5)
      { id: "G-K2.6", how: "test", desc: "TC-K2.T2.a 달 경계 창 시작 = 매달 1일 00:00 UTC (V20)", cmd: 'pnpm -C apps/server test -t "TC-K2.T2.a"', expectPassed: 1 },
      { id: "G-K2.7", how: "test", desc: "TC-K2.T2.b 새 달 첫 실행은 지난달 사용액을 넣지 않음", cmd: 'pnpm -C apps/server test -t "TC-K2.T2.b"', expectPassed: 1 },
      { id: "G-K2.24", how: "test", desc: "TC-K2.T2.c 달 바뀜은 저장한 마지막 실행 달로 판단 (Q5)", cmd: 'pnpm -C apps/server test -t "TC-K2.T2.c"', expectPassed: 1 },
      // K2.T6 1분 분배 (오늘 창 + 지난 날 저장, v5.7)
      { id: "G-K2.8", how: "test", desc: "TC-K2.T6.a 활성 키가 없는 회원은 OmniRoute 호출 없음", cmd: 'pnpm -C apps/server test -t "TC-K2.T6.a"', expectPassed: 1 },
      { id: "G-K2.9", how: "test", desc: "TC-K2.T6.b 예산이 바뀐 키만 setBudget", cmd: 'pnpm -C apps/server test -t "TC-K2.T6.b"', expectPassed: 1 },
      { id: "G-K2.10", how: "test", desc: "TC-K2.T6.c 분석 형식 오류면 예산을 하나도 바꾸지 않음", cmd: 'pnpm -C apps/server test -t "TC-K2.T6.c"', expectPassed: 1 },
      { id: "G-K2.11", how: "test", requires: ["local-services"], desc: "TC-K2.T6.d 두 키로 나눠 써도 회원 한도에서 둘 다 막힘 (계약)", cmd: 'pnpm test:contract -t "TC-K2.T6.d"', expectPassed: 1 },
      { id: "G-K2.12", how: "test", requires: ["local-services"], desc: "TC-K2.T6.e 삭제한 키 사용액이 새 키 몫을 줄임 (계약, V18)", cmd: 'pnpm test:contract -t "TC-K2.T6.e"', expectPassed: 1 },
      { id: "G-K2.13", how: "test", requires: ["local-services"], desc: "TC-K2.T6.f 사용액 0 키도 한도 도달 뒤 꺼짐 (계약, Q1)", cmd: 'pnpm test:contract -t "TC-K2.T6.f"', expectPassed: 1 },
      { id: "G-K2.25", how: "test", requires: ["local-services"], desc: "TC-K2.T6.j limit 키만 다시 켜기 (계약, Q1)", cmd: 'pnpm test:contract -t "TC-K2.T6.j"', expectPassed: 1 },
      { id: "G-K2.14", how: "test", requires: ["local-services"], desc: "TC-K2.T6.g 초과 폭 ≤ 한도 × 2 + 0.004878 (계약)", cmd: 'pnpm test:contract -t "TC-K2.T6.g"', expectPassed: 1 },
      { id: "G-K2.15", how: "cmd", requires: ["local-services"], desc: "TC-K2.T6.h 분배 소요 (보통 ≤ 30,000ms · 날이 바뀐 첫 분배 ≤ 55,000ms, V15)", cmd: "node tests/bench/analytics.mjs --rebalance --assert" },
      { id: "G-K2.26", how: "test", desc: "TC-K2.T6.k 1분 분배는 오늘 창 하나만 (V15)", cmd: 'pnpm -C apps/server test -t "TC-K2.T6.k"', expectPassed: 1 },
      // K2.T7 지난 날 저장 usage_daily·날 확정·하루 대조 (v5.7)
      { id: "G-K2.27", how: "test", desc: "TC-K2.T7.a 날이 바뀐 첫 분배가 어제를 확정 저장 (V15)", cmd: 'pnpm -C apps/server test -t "TC-K2.T7.a"', expectPassed: 1 },
      { id: "G-K2.28", how: "test", desc: "TC-K2.T7.b 하루 한 번 대조가 저장값을 덮고 차이를 알림 (V15)", cmd: 'pnpm -C apps/server test -t "TC-K2.T7.b"', expectPassed: 1 },
      { id: "G-K2.29", how: "test", desc: "TC-K2.T7.c 대조가 제한 시간에 걸리면 날 단위로 나눔", cmd: 'pnpm -C apps/server test -t "TC-K2.T7.c"', expectPassed: 1 },
      { id: "G-K2.30", how: "test", requires: ["local-services"], desc: "TC-K2.T7.d 저장 합 + 오늘 == 한 달 (계약, 오차 1e-9)", cmd: 'pnpm test:contract -t "TC-K2.T7.d"', expectPassed: 1 },
      { id: "G-K2.31", how: "test", requires: ["local-services"], desc: "TC-K2.T7.e usage_daily 다섯 DB", cmd: 'pnpm -C packages/db test:migrate -t "TC-K2.T7.e" --db sqlite,mysql,mariadb,pg,d1', expectPassed: 5 },
      // K2.T4 즉시 분배 진입점
      { id: "G-K2.16", how: "test", desc: "TC-K2.T4.a 즉시 분배는 그 회원 키 전부(삭제 포함)로 분석", cmd: 'pnpm -C apps/server test -t "TC-K2.T4.a"', expectPassed: 1 },
      { id: "G-K2.17", how: "test", desc: "TC-K2.T4.b 늦게 끝난 옛 계산이 새 계산을 덮지 않음", cmd: 'pnpm -C apps/server test -t "TC-K2.T4.b"', expectPassed: 1 },
      // 공통
      { id: "G-K2.18", how: "grep", desc: "어댑터 밖 OmniRoute 관리 호출 0", pattern: "/api/(keys|usage)", in: ["apps", "packages"], exclude: ["packages/omniroute/**"], op: "==", limit: 0 },
      { id: "G-K2.19", how: "cmd", desc: "타입 검사", cmd: "pnpm -r typecheck" },
      // K2.T5 CI 단계 잡과 ruleset 필수 검사
      { id: "G-K2.20", how: "grep", desc: "TC-K2.T5.a CI 단계 잡 (K2)", pattern: "^\\s+run: node scripts/gate\\.mjs K2\\b", in: [".github/workflows/ci.yml"], op: "==", limit: 1 },
      { id: "G-K2.22", how: "test", desc: "TC-K2.T6.i 분배 1분 등록·TC-K1.T4.b wrangler crons == JOBS crons", cmd: 'pnpm -C apps/server test -t "TC-K2.T6.i" && pnpm -C apps/server test -t "TC-K1.T4.b"', expectPassed: 2 },
      { id: "G-K2.23", how: "grep", desc: "1분 주기 상수", pattern: 'name: "budget_rebalance", cron: "\\* \\* \\* \\* \\*"', in: ["apps/server/src/jobs.ts"], op: "==", limit: 1 },
      { id: "G-K2.21", how: "cmd", desc: "TC-K2.T5.b ruleset 필수 검사 ⊇ ci.yml 잡 이름, 병합은 머지 커밋만", cmd: "node scripts/check-required-checks.mjs --repo henryj-dev/magnetosphere" },
      // K2 리뷰 고침 (M1~M4, L1~L4, 열린 질문)
      { id: "G-K2.32", how: "test", desc: "TC-K2.T1.f 사용액은 올림, 남은 한도는 내림 (리뷰 L2)", cmd: 'pnpm -C apps/server test -t "TC-K2.T1.f"', expectPassed: 1 },
      { id: "G-K2.33", how: "test", desc: "TC-K2.T7.f 이틀 넘는 공백 + 대조 시간 초과에도 사용액 == 한 달 합 (리뷰 M1)", cmd: 'pnpm -C apps/server test -t "TC-K2.T7.f"', expectPassed: 1 },
      { id: "G-K2.34", how: "test", desc: "TC-K2.T7.g 처음 설치 날 + 대조 시간 초과에도 사용액 == 한 달 합 (리뷰 M1)", cmd: 'pnpm -C apps/server test -t "TC-K2.T7.g"', expectPassed: 1 },
      { id: "G-K2.35", how: "test", desc: "TC-K2.T7.h 분할 하루 창 시간 초과는 그날만 미룸 (리뷰 L3)", cmd: 'pnpm -C apps/server test -t "TC-K2.T7.h"', expectPassed: 1 },
      { id: "G-K2.36", how: "test", desc: "TC-K2.T7.i 대조 응답에 없는 키의 저장값은 그대로 (리뷰 열린 질문)", cmd: 'pnpm -C apps/server test -t "TC-K2.T7.i"', expectPassed: 1 },
      { id: "G-K2.37", how: "test", desc: "TC-K2.T6.l 임대 안에 못 끝내는 회원 수도 두 tick 이면 모두 새 달 예산·끄기 (리뷰 M2)", cmd: 'pnpm -C apps/server test -t "TC-K2.T6.l"', expectPassed: 1 },
      { id: "G-K2.38", how: "test", desc: "TC-K2.T6.m 회원 하나의 예외가 다른 회원을 막지 않음 (리뷰 M2)", cmd: 'pnpm -C apps/server test -t "TC-K2.T6.m"', expectPassed: 1 },
      { id: "G-K2.39", how: "test", desc: "TC-K2.T6.o 임대를 잃은 setBudget 은 다음 실행이 다시 보냄 (리뷰 L1)", cmd: 'pnpm -C apps/server test -t "TC-K2.T6.o"', expectPassed: 1 },
      { id: "G-K2.40", how: "test", desc: "TC-K2.T6.p 무제한 전환 회원의 옛 예산은 clearBudget (리뷰 M3)", cmd: 'pnpm -C apps/server test -t "TC-K2.T6.p"', expectPassed: 1 },
      { id: "G-K2.41", how: "test", requires: ["local-services"], desc: "TC-K2.T6.n clearBudget 뒤 예산이 무제한 (계약, 리뷰 M3)", cmd: 'pnpm test:contract -t "TC-K2.T6.n"', expectPassed: 1 },
      { id: "G-K2.42", how: "grep", desc: "clearBudget 은 무제한 전환 경로 한 곳에서만 (리뷰 M3)", pattern: "\\.clearBudget\\(", in: ["apps/server/src"], op: "==", limit: 1 },
      { id: "G-K2.43", how: "test", desc: "TC-K2.T4.c 즉시 분배는 예산 실패를 삼키지 않음 (리뷰 M4)", cmd: 'pnpm -C apps/server test -t "TC-K2.T4.c"', expectPassed: 1 },
      { id: "G-K2.44", how: "cmd", desc: "재현 빨강: TC-K2.T1.f 는 Red 커밋에서 실패", cmd: "node scripts/check-red.mjs --check G-K2.32 --since seal:K1" },
      { id: "G-K2.45", how: "cmd", desc: "재현 빨강: TC-K2.T7.f 는 Red 커밋에서 실패", cmd: "node scripts/check-red.mjs --check G-K2.33 --since seal:K1" },
      { id: "G-K2.46", how: "cmd", desc: "재현 빨강: TC-K2.T7.g 는 Red 커밋에서 실패", cmd: "node scripts/check-red.mjs --check G-K2.34 --since seal:K1" },
      { id: "G-K2.47", how: "cmd", desc: "재현 빨강: TC-K2.T7.h 는 Red 커밋에서 실패", cmd: "node scripts/check-red.mjs --check G-K2.35 --since seal:K1" },
      { id: "G-K2.48", how: "cmd", desc: "재현 빨강: TC-K2.T7.i 는 Red 커밋에서 실패", cmd: "node scripts/check-red.mjs --check G-K2.36 --since seal:K1" },
      { id: "G-K2.49", how: "cmd", desc: "재현 빨강: TC-K2.T6.l 는 Red 커밋에서 실패", cmd: "node scripts/check-red.mjs --check G-K2.37 --since seal:K1" },
      { id: "G-K2.50", how: "cmd", desc: "재현 빨강: TC-K2.T6.m 는 Red 커밋에서 실패", cmd: "node scripts/check-red.mjs --check G-K2.38 --since seal:K1" },
      { id: "G-K2.51", how: "cmd", desc: "재현 빨강: TC-K2.T6.o 는 Red 커밋에서 실패", cmd: "node scripts/check-red.mjs --check G-K2.39 --since seal:K1" },
      { id: "G-K2.52", how: "cmd", desc: "재현 빨강: TC-K2.T6.p 는 Red 커밋에서 실패", cmd: "node scripts/check-red.mjs --check G-K2.40 --since seal:K1" },
      { id: "G-K2.53", how: "cmd", desc: "재현 빨강: TC-K2.T4.c 는 Red 커밋에서 실패", cmd: "node scripts/check-red.mjs --check G-K2.43 --since seal:K1" },
      { id: "G-K2.54", how: "cmd", desc: "재현 빨강: TC-K2.T6.i 는 Red 커밋에서 실패", cmd: "node scripts/check-red.mjs --check G-K2.22 --since seal:K1" },
      // K2 재검토 고침 (H1, M-a~c, L-a·L-b)
      { id: "G-K2.55", how: "test", desc: "TC-K2.T7.j 지난달 분할 대조 상태는 새 달에 지움 (재검토 L-b)", cmd: 'pnpm -C apps/server test -t "TC-K2.T7.j"', expectPassed: 1 },
      { id: "G-K2.56", how: "test", desc: "TC-K2.T6.t 늦게 도착한 clear·setBudget 뒤 다음 분배가 다시 건다 (재검토 H1)", cmd: 'pnpm -C apps/server test -t "TC-K2.T6.t"', expectPassed: 1 },
      { id: "G-K2.57", how: "test", desc: "TC-K2.T6.u 값을 모르는 예산도 무제한 전환 때 푼다 (재검토 M-a)", cmd: 'pnpm -C apps/server test -t "TC-K2.T6.u"', expectPassed: 1 },
      { id: "G-K2.58", how: "test", desc: "TC-K2.T6.q 매번 실패하는 회원은 정렬 뒤로 (재검토 M-b)", cmd: 'pnpm -C apps/server test -t "TC-K2.T6.q"', expectPassed: 1 },
      { id: "G-K2.59", how: "test", desc: "TC-K2.T6.r 계산이 깨진 회원 키 끄기·같은 알림 하루 한 번 (재검토 M-c)", cmd: 'pnpm -C apps/server test -t "TC-K2.T6.r"', expectPassed: 1 },
      { id: "G-K2.60", how: "test", desc: "TC-K2.T6.s 연속 10번 실패면 alert.rebalance_stalled 하루 한 번 (재검토 L-a)", cmd: 'pnpm -C apps/server test -t "TC-K2.T6.s"', expectPassed: 1 },
      { id: "G-K2.61", how: "cmd", desc: "재현 빨강: TC-K2.T7.j 는 Red 커밋에서 실패", cmd: "node scripts/check-red.mjs --check G-K2.55 --since seal:K1" },
      { id: "G-K2.62", how: "cmd", desc: "재현 빨강: TC-K2.T6.t 는 Red 커밋에서 실패", cmd: "node scripts/check-red.mjs --check G-K2.56 --since seal:K1" },
      { id: "G-K2.63", how: "cmd", desc: "재현 빨강: TC-K2.T6.u 는 Red 커밋에서 실패", cmd: "node scripts/check-red.mjs --check G-K2.57 --since seal:K1" },
      { id: "G-K2.64", how: "cmd", desc: "재현 빨강: TC-K2.T6.q 는 Red 커밋에서 실패", cmd: "node scripts/check-red.mjs --check G-K2.58 --since seal:K1" },
      { id: "G-K2.65", how: "cmd", desc: "재현 빨강: TC-K2.T6.r 는 Red 커밋에서 실패", cmd: "node scripts/check-red.mjs --check G-K2.59 --since seal:K1" },
      { id: "G-K2.66", how: "cmd", desc: "재현 빨강: TC-K2.T6.s 는 Red 커밋에서 실패", cmd: "node scripts/check-red.mjs --check G-K2.60 --since seal:K1" },
    ],
  },
  K3: {
    needs: ["K2"],
    waivable: false,
    strictTests: true,
    outputs: ["apps/server/src/keys/**", "apps/server/test/keys/**", "apps/server/test/contract/keys/**"],
    checks: [
      // K3.T1 목표 상태 함수 (순수 함수)
      { id: "G-K3.1", how: "test", desc: "TC-K3.T1.a 조합 표가 계획서 5.7 과 같다 (Q1)", cmd: 'pnpm -C apps/server test -t "TC-K3.T1.a"', expectPassed: 1 },
      { id: "G-K3.2", how: "test", desc: "TC-K3.T1.b 정지 해제·한도 회복은 user_status·limit 키만 켠다 (Q1)", cmd: 'pnpm -C apps/server test -t "TC-K3.T1.b"', expectPassed: 1 },
      // K3.T2 반영: 즉시 실행, 실패하면 큐
      { id: "G-K3.3", how: "test", desc: "TC-K3.T2.a 끄기는 응답 전에 OmniRoute 에 반영", cmd: 'pnpm -C apps/server test -t "TC-K3.T2.a"', expectPassed: 1 },
      { id: "G-K3.4", how: "test", desc: "TC-K3.T2.b OmniRoute 실패면 pending·1분 뒤 재시도 (Q2)", cmd: 'pnpm -C apps/server test -t "TC-K3.T2.b"', expectPassed: 1 },
      { id: "G-K3.5", how: "test", desc: "TC-K3.T2.c 목표가 켜짐이 아니면 켜지 않는다 (409)", cmd: 'pnpm -C apps/server test -t "TC-K3.T2.c"', expectPassed: 1 },
      { id: "G-K3.6", how: "test", desc: "TC-K3.T2.d 켜기 전에 예산을 건다", cmd: 'pnpm -C apps/server test -t "TC-K3.T2.d"', expectPassed: 1 },
      { id: "G-K3.18", how: "test", desc: "TC-K3.T2.e 삭제는 끄기 먼저, DELETE 는 끈 뒤 120,000ms (V18)", cmd: 'pnpm -C apps/server test -t "TC-K3.T2.e"', expectPassed: 1 },
      { id: "G-K3.20", how: "test", desc: "TC-K3.T2.f 작업 큐가 삭제 목표 키를 끄면 key.delete 를 끈 뒤 2분으로 (V18)", cmd: 'pnpm -C apps/server test -t "TC-K3.T2.f"', expectPassed: 1 },
      // K3.T3 정합성 점검 (5분)
      { id: "G-K3.7", how: "test", requires: ["local-services"], desc: "TC-K3.T3.a OmniRoute 에서 켜진 키의 목표가 꺼짐이면 점검이 끈다 (계약)", cmd: 'pnpm test:contract -t "TC-K3.T3.a"', expectPassed: 1 },
      { id: "G-K3.8", how: "test", desc: "TC-K3.T3.b 매핑 없는 m_ 키는 알리기만 (Q6)", cmd: 'pnpm -C apps/server test -t "TC-K3.T3.b"', expectPassed: 1 },
      { id: "G-K3.9", how: "test", requires: ["local-services"], desc: "TC-K3.T3.c scopes manage 가 붙은 키는 끄고 알린다 (계약, V10)", cmd: 'pnpm test:contract -t "TC-K3.T3.c"', expectPassed: 1 },
      { id: "G-K3.10", how: "test", desc: "TC-K3.T3.d 점검은 임대를 잃으면 멈춘다", cmd: 'pnpm -C apps/server test -t "TC-K3.T3.d"', expectPassed: 1 },
      { id: "G-K3.11", how: "test", requires: ["local-services"], desc: "TC-K3.T3.e 탈퇴 회원 키는 점검이 삭제한다 (V18, 네 DB)", cmd: 'pnpm -C apps/server test:db -t "TC-K3.T3.e" --db sqlite,mysql,mariadb,pg', expectPassed: 4 },
      { id: "G-K3.19", how: "test", desc: "TC-K3.T3.g 재시도를 다 쓴 키도 점검이 다시 맞춘다 (Q3)", cmd: 'pnpm -C apps/server test -t "TC-K3.T3.g"', expectPassed: 1 },
      { id: "G-K3.21", how: "test", desc: "TC-K3.T3.h 작업 큐가 남긴 어긋남을 점검이 맞춘다 (K1 메모)", cmd: 'pnpm -C apps/server test -t "TC-K3.T3.h"', expectPassed: 1 },
      { id: "G-K3.16", how: "test", desc: "TC-K3.T3.f 점검 5분 등록·TC-K1.T4.b wrangler crons == JOBS crons", cmd: 'pnpm -C apps/server test -t "TC-K3.T3.f" && pnpm -C apps/server test -t "TC-K1.T4.b"', expectPassed: 2 },
      { id: "G-K3.17", how: "grep", desc: "5분 주기 상수", pattern: 'name: "reconcile", cron: "\\*/5 \\* \\* \\* \\*"', in: ["apps/server/src/jobs.ts"], op: "==", limit: 1 },
      // 공통
      { id: "G-K3.12", how: "test", requires: ["local-services"], desc: "TC-S5.T2.i 어댑터 키 수정 본문에 scopes 없음 (1단계 회귀, 테스트 둘)", cmd: 'pnpm test:contract -t "TC-S5.T2.i"', expectPassed: 2 },
      { id: "G-K3.13", how: "cmd", desc: "타입 검사", cmd: "pnpm -r typecheck" },
      // 재현 빨강
      { id: "G-K3.22", how: "cmd", desc: "재현 빨강: TC-K3.T2.f 는 Red 커밋에서 실패", cmd: "node scripts/check-red.mjs --check G-K3.20 --since seal:K2" },
      { id: "G-K3.23", how: "cmd", desc: "재현 빨강: TC-K3.T3.f 는 Red 커밋에서 실패", cmd: "node scripts/check-red.mjs --check G-K3.16 --since seal:K2" },
      // K3 리뷰 고침 (#1~#9)
      { id: "G-K3.24", how: "test", requires: ["local-services"], desc: "TC-K3.T2.g 정지·해제 반영이 admin 이유를 건드리지 않는다 (네 DB, 리뷰 #9)", cmd: 'pnpm -C apps/server test:db -t "TC-K3.T2.g" --db sqlite,mysql,mariadb,pg', expectPassed: 4 },
      { id: "G-K3.25", how: "test", desc: "TC-K3.T2.h 분배의 limit 켜기 실패는 active·pending·큐 1분 뒤 (리뷰 #9)", cmd: 'pnpm -C apps/server test -t "TC-K3.T2.h"', expectPassed: 1 },
      { id: "G-K3.26", how: "test", desc: "TC-K3.T2.i 사라진 키(404)가 다른 키 켜기를 막지 않는다·alert.key_missing (리뷰 #6)", cmd: 'pnpm -C apps/server test -t "TC-K3.T2.i"', expectPassed: 1 },
      { id: "G-K3.27", how: "test", desc: "TC-K3.T3.i manage 범위 키는 이유와 상관없이 admin 고정 (리뷰 #1, V10)", cmd: 'pnpm -C apps/server test -t "TC-K3.T3.i"', expectPassed: 1 },
      { id: "G-K3.28", how: "test", desc: "TC-K3.T3.j 점검 시간 예산·이어 가기·끊겨도 알림 (리뷰 #2)", cmd: 'pnpm -C apps/server test -t "TC-K3.T3.j"', expectPassed: 1 },
      { id: "G-K3.29", how: "test", requires: ["local-services"], desc: "TC-K3.T3.k listKeys 는 limit 없이 모든 키 (계약, V28, 리뷰 #3)", cmd: 'pnpm test:contract -t "TC-K3.T3.k"', expectPassed: 1 },
      { id: "G-K3.30", how: "test", desc: "TC-K3.T3.l 키 목록이 total 보다 적으면 형식 오류 (V28, 리뷰 #3)", cmd: 'pnpm -C packages/omniroute test -t "TC-K3.T3.l"', expectPassed: 1 },
      { id: "G-K3.31", how: "test", desc: "TC-K3.T3.m 옛 목록 값으로 synced 를 적지 않는다 (리뷰 #4)", cmd: 'pnpm -C apps/server test -t "TC-K3.T3.m"', expectPassed: 1 },
      { id: "G-K3.32", how: "test", desc: "TC-K3.T3.n 이유 없는 꺼진 키는 alert.key_stuck 하루 한 번 (리뷰 #8)", cmd: 'pnpm -C apps/server test -t "TC-K3.T3.n"', expectPassed: 1 },
      { id: "G-K3.33", how: "cmd", desc: "재현 빨강: TC-K3.T2.i 는 Red 커밋에서 실패", cmd: "node scripts/check-red.mjs --check G-K3.26 --since seal:K2" },
      { id: "G-K3.34", how: "cmd", desc: "재현 빨강: TC-K3.T3.i 는 Red 커밋에서 실패", cmd: "node scripts/check-red.mjs --check G-K3.27 --since seal:K2" },
      { id: "G-K3.35", how: "cmd", desc: "재현 빨강: TC-K3.T3.j 는 Red 커밋에서 실패", cmd: "node scripts/check-red.mjs --check G-K3.28 --since seal:K2" },
      { id: "G-K3.36", how: "cmd", desc: "재현 빨강: TC-K3.T3.l 는 Red 커밋에서 실패", cmd: "node scripts/check-red.mjs --check G-K3.30 --since seal:K2" },
      { id: "G-K3.37", how: "cmd", desc: "재현 빨강: TC-K3.T3.m 는 Red 커밋에서 실패", cmd: "node scripts/check-red.mjs --check G-K3.31 --since seal:K2" },
      { id: "G-K3.38", how: "cmd", desc: "재현 빨강: TC-K3.T3.n 는 Red 커밋에서 실패", cmd: "node scripts/check-red.mjs --check G-K3.32 --since seal:K2" },
      // K3.T4 CI 단계 잡과 ruleset 필수 검사
      { id: "G-K3.14", how: "grep", desc: "TC-K3.T4.a CI 단계 잡 (K3)", pattern: "^\\s+run: node scripts/gate\\.mjs K3\\b", in: [".github/workflows/ci.yml"], op: "==", limit: 1 },
      { id: "G-K3.15", how: "cmd", desc: "TC-K3.T4.b ruleset 필수 검사 ⊇ ci.yml 잡 이름, 병합은 머지 커밋만", cmd: "node scripts/check-required-checks.mjs --repo henryj-dev/magnetosphere" },
    ],
  },
  K4: {
    needs: ["K3"],
    waivable: false,
    strictTests: true,
    outputs: ["apps/server/src/routes/**", "apps/server/test/routes/**", "apps/server/test/contract/routes/**"],
    checks: [
      // K4.T1 발급 POST /api/me/keys
      { id: "G-K4.1", how: "test", desc: "TC-K4.T1.a 발급 순서가 5.2 와 같다 (예산이 성공한 뒤에만 켠다)", cmd: 'pnpm -C apps/server test -t "TC-K4.T1.a"', expectPassed: 1 },
      { id: "G-K4.2", how: "test", desc: "TC-K4.T1.b 끄기·예산·켜기 어디서 실패해도 만든 키를 지운다", cmd: 'pnpm -C apps/server test -t "TC-K4.T1.b"', expectPassed: 1 },
      { id: "G-K4.3", how: "test", desc: "TC-K4.T1.c 되돌리기도 실패하면 key.rollback, 켜진 채 남지 않는다", cmd: 'pnpm -C apps/server test -t "TC-K4.T1.c"', expectPassed: 1 },
      { id: "G-K4.4", how: "test", desc: "TC-K4.T1.d 거부 조건은 OmniRoute 를 부르지 않는다", cmd: 'pnpm -C apps/server test -t "TC-K4.T1.d"', expectPassed: 1 },
      { id: "G-K4.5", how: "test", desc: "TC-K4.T1.e 최대 개수는 기본 2, 비활성 포함, 삭제 제외, 줄여도 기존 키 유지", cmd: 'pnpm -C apps/server test -t "TC-K4.T1.e"', expectPassed: 1 },
      { id: "G-K4.6", how: "test", requires: ["local-services"], desc: "TC-K4.T1.f 동시 발급 10건은 최대 개수를 넘지 않는다 (Node 네 DB)", cmd: 'pnpm -C apps/server test:db -t "TC-K4.T1.f" --db sqlite,mysql,mariadb,pg', expectPassed: 4 },
      { id: "G-K4.7", how: "test", requires: ["local-services"], desc: "TC-K4.T1.f 동시 발급 10건은 최대 개수를 넘지 않는다 (Workers + D1)", cmd: 'pnpm -C apps/server test:workers -t "TC-K4.T1.f"', expectPassed: 1 },
      { id: "G-K4.8", how: "test", desc: "TC-K4.T1.g · h 원문 미저장·OmniRoute 키 이름 규칙", cmd: 'pnpm -C apps/server test -t "TC-K4.T1.[gh]"', expectPassed: 2 },
      { id: "G-K4.9", how: "test", desc: "TC-K4.T1.i 목록은 남은 발급 가능 개수를 준다", cmd: 'pnpm -C apps/server test -t "TC-K4.T1.i"', expectPassed: 1 },
      // K4.T7 이름 변경·끄기·켜기·재발급·삭제 (v5.6)
      { id: "G-K4.10", how: "test", desc: "TC-K4.T7.a 이름 변경은 OmniRoute 를 부르지 않는다", cmd: 'pnpm -C apps/server test -t "TC-K4.T7.a"', expectPassed: 1 },
      { id: "G-K4.11", how: "test", desc: "TC-K4.T7.b 삭제는 바로 끄고 행을 남기고 DELETE 는 끈 뒤 120,000ms (V18)", cmd: 'pnpm -C apps/server test -t "TC-K4.T7.b"', expectPassed: 1 },
      { id: "G-K4.12", how: "test", desc: "TC-K4.T7.c 재발급은 새 키 + 옛 키 삭제, 한도를 초기화하지 않는다 (V19)", cmd: 'pnpm -C apps/server test -t "TC-K4.T7.c"', expectPassed: 1 },
      { id: "G-K4.13", how: "test", desc: "TC-K4.T7.d 남의 키는 404 이고 OmniRoute 를 부르지 않는다", cmd: 'pnpm -C apps/server test -t "TC-K4.T7.d"', expectPassed: 1 },
      { id: "G-K4.14", how: "test", desc: "TC-K4.T7.e 회원이 끈 키만 회원이 켠다 (admin 403, limit 409)", cmd: 'pnpm -C apps/server test -t "TC-K4.T7.e"', expectPassed: 1 },
      { id: "G-K4.28", how: "test", desc: "TC-K4.T7.f 재발급도 발급 조건을 본다", cmd: 'pnpm -C apps/server test -t "TC-K4.T7.f"', expectPassed: 1 },
      // K4.T3 관리자 한도·최대 개수 API
      { id: "G-K4.15", how: "test", desc: "TC-K4.T3.a 관리자만 바꾸고, 바꾸면 즉시 분배·audit_log", cmd: 'pnpm -C apps/server test -t "TC-K4.T3.a"', expectPassed: 1 },
      { id: "G-K4.16", how: "test", desc: "TC-K4.T3.b 잘못된 한도·최대 개수는 400, DB 변화 0", cmd: 'pnpm -C apps/server test -t "TC-K4.T3.b"', expectPassed: 1 },
      // K4.T4 CSRF 와 발급 요청 수 제한
      { id: "G-K4.17", how: "test", desc: "TC-K4.T4.a 다른 출처의 변경 요청은 403", cmd: 'pnpm -C apps/server test -t "TC-K4.T4.a"', expectPassed: 1 },
      { id: "G-K4.18", how: "test", requires: ["local-services"], desc: "TC-K4.T4.b 발급 요청 수 제한 회원 10·IP 30 /시간, 넘으면 429 (Q4, 네 DB)", cmd: 'pnpm -C apps/server test:db -t "TC-K4.T4.b" --db sqlite,mysql,mariadb,pg', expectPassed: 4 },
      // K4.T5 실제 OmniRoute 로 수명주기 (계약)
      { id: "G-K4.19", how: "test", requires: ["local-services"], desc: "TC-K4.T5.a 발급·끄기·켜기·삭제 (계약, V11·V18)", cmd: 'pnpm test:contract -t "TC-K4.T5.a"', expectPassed: 1 },
      { id: "G-K4.20", how: "test", requires: ["local-services"], desc: "TC-K4.T5.b 남은 한도 0 회원 발급 거부 (계약)", cmd: 'pnpm test:contract -t "TC-K4.T5.b"', expectPassed: 1 },
      // 공통
      { id: "G-K4.21", how: "grep", desc: "발급 순서 (5.2 의 2~5번) 기대값", pattern: '"createKey", "setKeyActive\\(false\\)", "setBudget", "setKeyActive\\(true\\)"', in: ["apps/server/test/routes"], op: "==", limit: 1 },
      { id: "G-K4.22", how: "grep", desc: "원문 키 저장 칼럼 없음", pattern: "\\b(key_raw|raw_key|secret_key)\\b", in: ["packages/db/src/schema"], op: "==", limit: 0 },
      { id: "G-K4.23", how: "grep", desc: "어댑터 밖 OmniRoute 관리 호출 0 (1단계 G-S5.9 와 같은 규칙)", pattern: "/api/(keys|usage)", in: ["apps", "packages"], exclude: ["packages/omniroute/**"], op: "==", limit: 0 },
      { id: "G-K4.24", how: "grep", desc: "시드 기본값 최대 키 2", pattern: "default_max_keys: 2,", in: ["packages/db/src/seed.ts"], op: "==", limit: 1 },
      { id: "G-K4.29", how: "grep", desc: "시드 기본값 월 한도 $5", pattern: "default_limit_usd: 5,", in: ["packages/db/src/seed.ts"], op: "==", limit: 1 },
      { id: "G-K4.25", how: "cmd", desc: "타입 검사", cmd: "pnpm -r typecheck" },
      // K4 보안 리뷰 고침 (M1·M2·L1~L4, 시험 보강)
      { id: "G-K4.30", how: "test", desc: "TC-K4.T7.g 발급 중인 자리 행은 회원이 바꾸지 못한다 (리뷰 M1)", cmd: 'pnpm -C apps/server test -t "TC-K4.T7.g"', expectPassed: 1 },
      { id: "G-K4.31", how: "test", desc: "TC-K4.T1.j 오래된 자리 행은 정합성 점검이 지운다 (리뷰 M2)", cmd: 'pnpm -C apps/server test -t "TC-K4.T1.j"', expectPassed: 1 },
      { id: "G-K4.32", how: "test", desc: "TC-K4.T1.k 죽은 발급의 매핑 없는 m_ 키는 끄고 2분 뒤 지운다 (리뷰 M2)", cmd: 'pnpm -C apps/server test -t "TC-K4.T1.k"', expectPassed: 1 },
      { id: "G-K4.33", how: "test", desc: "TC-K4.T4.c 키 변경 요청은 회원당 분당 30회 (리뷰 L3)", cmd: 'pnpm -C apps/server test -t "TC-K4.T4.c"', expectPassed: 1 },
      { id: "G-K4.34", how: "test", desc: "TC-K4.T4.d 발급 IP 칸은 IPv6 /64 (리뷰 L4)", cmd: 'pnpm -C apps/server test -t "TC-K4.T4.d"', expectPassed: 1 },
      { id: "G-K4.35", how: "test", requires: ["local-services"], desc: "TC-K4.T1.l 자리 잡기 직접 동시 10건 (Node 네 DB)", cmd: 'pnpm -C apps/server test:db -t "TC-K4.T1.l" --db sqlite,mysql,mariadb,pg', expectPassed: 4 },
      { id: "G-K4.36", how: "test", requires: ["local-services"], desc: "TC-K4.T1.l 자리 잡기 직접 동시 10건 (Workers + D1)", cmd: 'pnpm -C apps/server test:workers -t "TC-K4.T1.l"', expectPassed: 1 },
      { id: "G-K4.37", how: "cmd", desc: "재현 빨강: TC-K4.T1.c 는 Red 커밋에서 실패", cmd: "node scripts/check-red.mjs --check G-K4.3 --since seal:K3" },
      { id: "G-K4.38", how: "cmd", desc: "재현 빨강: TC-K4.T7.g 는 Red 커밋에서 실패", cmd: "node scripts/check-red.mjs --check G-K4.30 --since seal:K3" },
      { id: "G-K4.39", how: "cmd", desc: "재현 빨강: TC-K4.T1.j 는 Red 커밋에서 실패", cmd: "node scripts/check-red.mjs --check G-K4.31 --since seal:K3" },
      { id: "G-K4.40", how: "cmd", desc: "재현 빨강: TC-K4.T1.k 는 Red 커밋에서 실패", cmd: "node scripts/check-red.mjs --check G-K4.32 --since seal:K3" },
      { id: "G-K4.41", how: "cmd", desc: "재현 빨강: TC-K4.T1.a 는 Red 커밋에서 실패", cmd: "node scripts/check-red.mjs --check G-K4.1 --since seal:K3" },
      { id: "G-K4.42", how: "cmd", desc: "재현 빨강: TC-K4.T7.c 는 Red 커밋에서 실패", cmd: "node scripts/check-red.mjs --check G-K4.12 --since seal:K3" },
      { id: "G-K4.43", how: "cmd", desc: "재현 빨강: TC-K4.T7.e 는 Red 커밋에서 실패", cmd: "node scripts/check-red.mjs --check G-K4.14 --since seal:K3" },
      { id: "G-K4.44", how: "cmd", desc: "재현 빨강: TC-K4.T4.c 는 Red 커밋에서 실패", cmd: "node scripts/check-red.mjs --check G-K4.33 --since seal:K3" },
      { id: "G-K4.45", how: "cmd", desc: "재현 빨강: TC-K4.T4.d 는 Red 커밋에서 실패", cmd: "node scripts/check-red.mjs --check G-K4.34 --since seal:K3" },
      // K4.T6 CI 단계 잡과 ruleset 필수 검사
      { id: "G-K4.26", how: "grep", desc: "TC-K4.T6.a CI 단계 잡 (K4)", pattern: "^\\s+run: node scripts/gate\\.mjs K4\\b", in: [".github/workflows/ci.yml"], op: "==", limit: 1 },
      { id: "G-K4.27", how: "cmd", desc: "TC-K4.T6.b ruleset 필수 검사 ⊇ ci.yml 잡 이름, 병합은 머지 커밋만", cmd: "node scripts/check-required-checks.mjs --repo henryj-dev/magnetosphere" },
    ],
  },
  K5: {
    needs: ["K4"],
    waivable: false,
    strictTests: true,
    outputs: ["tests/e2e/keys/**", "tests/e2e/claude-code/**"],
    checks: [
      // K5.T1 Claude Code 가 발급 키로 동작한다
      { id: "G-K5.1", how: "cmd", requires: ["local-services"], desc: "TC-K5.T1.a Claude Code 가 회원 앱이 발급한 키로 응답을 받는다", cmd: "pnpm e2e --combo docker-sqlite --scenario claude-code" },
      { id: "G-K5.2", how: "grep", desc: "Claude Code 버전 고정", pattern: '"@anthropic-ai/claude-code": "[0-9]+\\.[0-9]+\\.[0-9]+"', in: ["tests/e2e/claude-code/package.json"], op: "==", limit: 1 },
      // K5.T2 여섯 조합 키 시나리오 (TC-K5.T2.a~d). CI 는 e2e 매트릭스 잡이 같은 명령으로 돈다 (K5 잡은 --skip-ids 로 뺀다)
      { id: "G-K5.3", how: "cmd", requires: ["local-services"], desc: "TC-K5.T2.a~d 키 시나리오: docker-sqlite", cmd: "pnpm e2e --combo docker-sqlite --scenario keys" },
      { id: "G-K5.4", how: "cmd", requires: ["local-services"], desc: "TC-K5.T2.a~d 키 시나리오: docker-mysql", cmd: "pnpm e2e --combo docker-mysql --scenario keys" },
      { id: "G-K5.5", how: "cmd", requires: ["local-services"], desc: "TC-K5.T2.a~d 키 시나리오: docker-pg", cmd: "pnpm e2e --combo docker-pg --scenario keys" },
      { id: "G-K5.6", how: "cmd", requires: ["local-services"], desc: "TC-K5.T2.a~d 키 시나리오: workers-d1", cmd: "pnpm e2e --combo workers-d1 --scenario keys" },
      { id: "G-K5.7", how: "cmd", requires: ["local-services"], desc: "TC-K5.T2.a~d 키 시나리오: workers-mysql", cmd: "pnpm e2e --combo workers-mysql --scenario keys" },
      { id: "G-K5.8", how: "cmd", requires: ["local-services"], desc: "TC-K5.T2.a~d 키 시나리오: workers-pg", cmd: "pnpm e2e --combo workers-pg --scenario keys" },
      // K5.T3 CI 매트릭스가 키 시나리오를 돈다
      { id: "G-K5.9", how: "cmd", desc: "TC-K5.T3.a·b 매트릭스가 여섯 조합 키 시나리오를 돈다 (음성 대조 포함)", cmd: "node scripts/check-ci-matrix.mjs --expect 6 && node scripts/check-ci-matrix.mjs --fixture test/fixtures/ci-guard/e2e-keys-missing.yml --expect 6 --expect-fail" },
      { id: "G-K5.10", how: "cmd", desc: "재현 빨강: TC-K5.T3.a 는 Red 커밋에서 실패", cmd: "node scripts/check-red.mjs --check G-K5.9 --since seal:K4" },
      // K5.T4 CI 단계 잡과 ruleset 필수 검사
      { id: "G-K5.11", how: "grep", desc: "TC-K5.T4.a CI 단계 잡 (K5)", pattern: "^\\s+run: node scripts/gate\\.mjs K5\\b", in: [".github/workflows/ci.yml"], op: "==", limit: 1 },
      { id: "G-K5.12", how: "cmd", desc: "TC-K5.T4.b ruleset 필수 검사 ⊇ ci.yml 잡 이름, 병합은 머지 커밋만", cmd: "node scripts/check-required-checks.mjs --repo henryj-dev/magnetosphere" },
    ],
  },
  K6: {
    needs: ["K5"],
    waivable: false,
    strictTests: true,
    outputs: [],
    checks: [
      // K6.T1 임시 코드 회수. 시험 주입점은 함수 인자(now·fetch·signal)만. 환경 변수로 켜는 시험 갈림길·가짜 시계를 운영 코드에 두지 않는다
      { id: "G-K6.1", how: "grep", desc: "TC-K6.T1.a 운영 코드에 시험 갈림길 0", pattern: "process\\.env\\.(TEST_|E2E_|FAKE_|MG_TEST)|globalThis\\.__test", in: ["apps/server/src", "packages/auth/src", "packages/db/src", "packages/omniroute/src", "packages/runtime/src"], op: "==", limit: 0 },
      // G-S7.3 과 같은 패턴·제외. 1단계 경로에 2단계가 더한 test/ 를 함께 본다
      { id: "G-K6.2", how: "grep", desc: "TC-K6.T1.b 꺼진 테스트·미구현 표식 0 (2단계 경로 포함)", pattern: "\\.(only|skip|skipIf|todo)\\(|\\.(skip|only)\\.|runIf\\(|\\b(skip|todo)\\s*:\\s*true|\\b(xit|xdescribe|xtest)\\(|TODO|FIXME|not implemented", in: ["apps", "packages", "tests", "scripts", "test"], exclude: ["apps/web/build/**", "**/.svelte-kit/**", "**/.wrangler/**", "**/dist/**", "scripts/gate.test.mjs"], op: "==", limit: 0 },
      // K6.T2 운영 문서에 계획서 5.3 한계 두 줄
      { id: "G-K6.3", how: "grep", desc: "TC-K6.T2.a 운영 문서에 몰아 쓰기 초과 폭", pattern: "남은 한도 × 동시에 쓰는 키 수", in: ["deploy/README.md"], op: "==", limit: 1 },
      // K6.T4 끝난 작업 정리 (K1 리뷰 #9 백로그 결정: 주기 정리, 30일). 실패 작업은 지우지 않는다
      { id: "G-K6.10", how: "test", requires: ["local-services"], desc: "TC-K6.T4.a done_at 30일 넘은 작업만 지움·실패 작업 남김·펜싱 (네 DB)", cmd: 'pnpm -C apps/server test:db -t "TC-K6.T4.a" --db sqlite,mysql,mariadb,pg', expectPassed: 4 },
      { id: "G-K6.11", how: "test", desc: "TC-K6.T4.b 1분 작업 큐 실행기가 정리를 부른다", cmd: 'pnpm -C apps/server test -t "TC-K6.T4.b"', expectPassed: 1 },
      { id: "G-K6.12", how: "cmd", desc: "재현 빨강: TC-K6.T4.a 는 Red 커밋에서 실패", cmd: "node scripts/check-red.mjs --check G-K6.10 --since seal:K5" },
      { id: "G-K6.13", how: "cmd", desc: "재현 빨강: TC-K6.T4.b 는 Red 커밋에서 실패", cmd: "node scripts/check-red.mjs --check G-K6.11 --since seal:K5" },
      // K6.T5 키 시나리오 누락은 S6 조합 불일치(combo-set)와 다른 코드 [keys-scenario] (K5 리뷰 L4)
      { id: "G-K6.15", how: "cmd", desc: "TC-K6.T5.a 키 시나리오 누락 음성 대조는 [keys-scenario] 로만 잡힌다", cmd: "node scripts/check-ci-matrix.mjs --expect 6 && node scripts/check-ci-matrix.mjs --fixture test/fixtures/ci-guard/e2e-keys-missing.yml --expect 6 --expect-fail" },
      { id: "G-K6.16", how: "cmd", desc: "재현 빨강: TC-K6.T5.a 는 Red 커밋에서 실패", cmd: "node scripts/check-red.mjs --check G-K6.15 --since seal:K5" },
      { id: "G-K6.14", how: "grep", desc: "TC-K6.T2.a 운영 문서에 비용은 추정치", pattern: "추정", in: ["deploy/README.md"], op: ">=", limit: 1 },
    ],
  },
};
