// 실행판(docs/plan/phase1-todo.md) GATE 의 검사 정의. 검사 추가는 이 데이터만 고친다.
// 검사가 빈 단계는 gate 가 실행·봉인을 거부한다. 각 단계 검사는 그 단계를 시작할 때 실행판 GATE 표대로 채운다.
// outputs 는 --assert-order 가 잠긴 단계의 변경을 잡는 데 쓰는 글롭이다.
// requires: ["local-services"] 는 이 컴퓨터에서만 띄워 둔 서비스가 필요한 검사다 (시험용 OmniRoute·Keycloak·
// mailpit, docker 테스트 DB). CI 의 봉인 재검은 --skip-requires local-services 로 이 검사를 건너뛴다.
// 이 검사들은 S7 의 CI 매트릭스에서 서비스를 띄워 다시 돈다.

const nodeTest = (file, tc) => `node --test --test-reporter=tap --test-name-pattern="${tc}" ${file}`;

export const GATES = {
  S0: {
    needs: [],
    waivable: false,
    outputs: [
      "package.json", "pnpm-workspace.yaml", ".nvmrc", ".gitignore", "LICENSE",
      "apps/*/package.json", "packages/*/package.json",
      "scripts/check-workspace.mjs", "scripts/gate.mjs", "scripts/gate.test.mjs", "scripts/hook.test.mjs",
      "gates/gates.config.mjs", ".githooks/**", ".github/workflows/gate.yml",
    ],
    checks: [
      { id: "G-S0.1", how: "cmd", desc: "TC-S0.T1.a 워크스페이스 패키지 여섯", cmd: "node scripts/check-workspace.mjs" },
      { id: "G-S0.2", how: "test", desc: "TC-S0.T2.a 선행 미봉인 거부", cmd: nodeTest("scripts/gate.test.mjs", "TC-S0.T2.a") },
      { id: "G-S0.3", how: "test", desc: "TC-S0.T2.b 되돌리면 봉인 무효", cmd: nodeTest("scripts/gate.test.mjs", "TC-S0.T2.b") },
      { id: "G-S0.4", how: "test", desc: "TC-S0.T2.c --seal 재검", cmd: nodeTest("scripts/gate.test.mjs", "TC-S0.T2.c") },
      { id: "G-S0.5", how: "test", desc: "TC-S0.T2.d 검사 종류마다 이빨", cmd: nodeTest("scripts/gate.test.mjs", "TC-S0.T2.d") },
      { id: "G-S0.6", how: "test", desc: "TC-S0.T2.e 면제 조건", cmd: nodeTest("scripts/gate.test.mjs", "TC-S0.T2.e") },
      { id: "G-S0.7", how: "test", desc: "TC-S0.T2.f --assert-order", cmd: nodeTest("scripts/gate.test.mjs", "TC-S0.T2.f") },
      { id: "G-S0.8", how: "test", desc: "TC-S0.T3.a pre-push 훅 거부", cmd: nodeTest("scripts/hook.test.mjs", "TC-S0.T3.a") },
      { id: "G-S0.9", how: "cmd", desc: "봉인 디렉터리가 무시되지 않음", cmd: "git check-ignore -q gates/seals/S0.json", expectExit: 1 },
      { id: "G-S0.10", how: "test", desc: "TC-S0.T2.g 위조 봉인 무효", cmd: nodeTest("scripts/gate.test.mjs", "TC-S0.T2.g") },
      { id: "G-S0.11", how: "test", desc: "TC-S0.T2.h --verify-seals --rerun", cmd: nodeTest("scripts/gate.test.mjs", "TC-S0.T2.h") },
      { id: "G-S0.12", how: "test", desc: "TC-S0.T2.i 설정 변경으로 우회 불가", cmd: nodeTest("scripts/gate.test.mjs", "TC-S0.T2.i") },
      { id: "G-S0.13", how: "test", desc: "TC-S0.T2.j --head 지정", cmd: nodeTest("scripts/gate.test.mjs", "TC-S0.T2.j") },
      { id: "G-S0.14", how: "test", desc: "TC-S0.T3.b 다른 브랜치 push 거부", cmd: nodeTest("scripts/hook.test.mjs", "TC-S0.T3.b") },
      { id: "G-S0.15", how: "test", desc: "CI 테스트 명령", cmd: 'node --test --test-reporter=tap "scripts/*.test.mjs"' },
    ],
  },
  S1: {
    needs: ["S0"],
    waivable: false,
    outputs: ["spikes/**", "docs/verify/**", "scripts/check-verify.mjs", "scripts/check-verify.test.mjs"],
    checks: [
      { id: "G-S1.1", how: "cmd", requires: ["local-services"], desc: "TC-S1.T1.a 최소 범위 토큰으로 관리 호출 7개", cmd: "node spikes/v10/run.mjs --assert min" },
      { id: "G-S1.2", how: "cmd", requires: ["local-services"], desc: "TC-S1.T1.b 더 낮은 범위는 실패", cmd: "node spikes/v10/run.mjs --assert lower-fails" },
      { id: "G-S1.3", how: "cmd", requires: ["local-services"], desc: "TC-S1.T2.a 끈 키 즉시 거부", cmd: "node spikes/v11/run.mjs --assert" },
      { id: "G-S1.4", how: "cmd", requires: ["local-services"], desc: "TC-S1.T3.a 허용 목록이 실제 요청을 덮음", cmd: "node spikes/v16/check.mjs covers" },
      { id: "G-S1.5", how: "cmd", desc: "TC-S1.T3.b 관리 별칭은 허용 목록 밖", cmd: "node spikes/v16/check.mjs deny" },
      { id: "G-S1.6", how: "test", requires: ["local-services"], desc: "TC-S1.T4.a input:false 권한 칼럼 보호", cmd: 'pnpm -C spikes/v17 test -t "TC-S1.T4.a"' },
      { id: "G-S1.7", how: "test", requires: ["local-services"], desc: "TC-S1.T4.b 대조군", cmd: 'pnpm -C spikes/v17 test -t "TC-S1.T4.b"' },
      { id: "G-S1.8", how: "cmd", requires: ["local-services"], desc: "TC-S1.T5.a 비밀 값 전부로 운영 모드 시작", cmd: "node spikes/v21/run.mjs all" },
      { id: "G-S1.9", how: "cmd", requires: ["local-services"], desc: "TC-S1.T5.b 각 비밀 값의 필수 여부", cmd: "node spikes/v21/run.mjs each" },
      { id: "G-S1.10", how: "test", requires: ["local-services"], desc: "TC-S1.T6.a 네 DB 가입·로그인·세션", cmd: 'pnpm -C spikes/v26 test -t "TC-S1.T6.a"' },
      { id: "G-S1.11", how: "test", requires: ["local-services"], desc: "TC-S1.T6.b resolveUser 트랜잭션 롤백", cmd: 'pnpm -C spikes/v26 test -t "TC-S1.T6.b"' },
      { id: "G-S1.12", how: "test", requires: ["local-services"], desc: "TC-S1.T6.c 대소문자 이메일 중복", cmd: 'pnpm -C spikes/v26 test -t "TC-S1.T6.c"' },
      { id: "G-S1.13", how: "cmd", requires: ["local-services"], desc: "TC-S1.T7.a Workers + MySQL", cmd: "node spikes/v27/probe.mjs" },
      { id: "G-S1.14", how: "cmd", desc: "확인 파일 7개 존재·모양", cmd: "node scripts/check-verify.mjs present" },
      { id: "G-S1.15", how: "cmd", desc: "설계를 막는 결과 없음", cmd: "node scripts/check-verify.mjs unblocked" },
      { id: "G-S1.16", how: "cmd", desc: "막았던 결과는 현재 계획서 버전을 가리킴", cmd: "node scripts/check-verify.mjs resolved" },
      { id: "G-S1.17", how: "test", desc: "TC-S1.G.a~d 확인 결과 검사기 음성 대조", cmd: "node --test --test-reporter=tap scripts/check-verify.test.mjs" },
    ],
  },
  S2: {
    needs: ["S1"],
    waivable: false,
    outputs: [
      "packages/db/package.json", "packages/db/src/**", "packages/db/scripts/**", "packages/db/migrations/**", "packages/db/test/**",
      "packages/db/*.config.ts", "scripts/schema-lint.mjs", "test/fixtures/**", "docker-compose.test.yml",
    ],
    checks: [
      { id: "G-S2.1", how: "cmd", desc: "TC-S2.T1.a 생성물이 공통 정의와 같음", cmd: "pnpm -C packages/db gen && git diff --exit-code packages/db/src/schema/" },
      { id: "G-S2.2", how: "cmd", desc: "TC-S2.T1.b 스키마 규칙 위반 0", cmd: "node scripts/schema-lint.mjs" },
      { id: "G-S2.3", how: "cmd", desc: "TC-S2.T1.c 린트 음성 대조 (픽스처 위반 8)", cmd: "node scripts/schema-lint.mjs --fixture test/fixtures/bad-schema.ts --expect 8" },
      { id: "G-S2.4", how: "test", desc: "TC-S2.T2.a 시드 기본값", cmd: 'pnpm -C packages/db test -t "TC-S2.T2.a"' },
      { id: "G-S2.5", how: "test", desc: "TC-S2.T2.b 시드가 운영자 값을 덮지 않음", cmd: 'pnpm -C packages/db test -t "TC-S2.T2.b"' },
      { id: "G-S2.6", how: "test", requires: ["local-services"], desc: "TC-S2.T3.a 다섯 DB 빈 상태 → 최신 마이그레이션", cmd: "pnpm -C packages/db test:migrate --db sqlite,mysql,mariadb,pg,d1" },
      { id: "G-S2.7", how: "cmd", desc: "TC-S2.T3.b 마이그레이션과 스키마가 같음", cmd: "pnpm -C packages/db check:drift" },
      { id: "G-S2.8", how: "test", requires: ["local-services"], desc: "TC-S2.T3.c 이메일 소문자 저장·대소문자 중복 거부", cmd: 'pnpm -C packages/db test:migrate -t "TC-S2.T3.c"' },
      { id: "G-S2.9", how: "grep", desc: "MySQL id 는 VARCHAR(36)", pattern: 'varchar\\("id", \\{ length: 36', in: ["packages/db/src/schema/mysql.ts"], op: ">=", limit: 4 },
      { id: "G-S2.10", how: "grep", desc: "지원 DB 최소 버전 고정", pattern: "mysql:8.0|mariadb:10.11|postgres:14", in: ["docker-compose.test.yml"], op: "==", limit: 3 },
      { id: "G-S2.11", how: "test", requires: ["local-services"], desc: "TC-S2.T3.e 2038 년 이후 시각 왕복", cmd: 'pnpm -C packages/db test:migrate -t "TC-S2.T3.e"' },
      { id: "G-S2.12", how: "test", requires: ["local-services"], desc: "TC-S2.T3.f 토큰·식별자 대소문자 구분", cmd: 'pnpm -C packages/db test:migrate -t "TC-S2.T3.f"' },
      { id: "G-S2.13", how: "test", requires: ["local-services"], desc: "TC-S2.T3.d 마이그레이션 DB 구조 = 스키마 DB 구조", cmd: 'pnpm -C packages/db test:migrate -t "TC-S2.T3.d"' },
    ],
  },
  S3: {
    needs: ["S2"],
    waivable: false,
    outputs: [
      "packages/auth/src/**", "packages/auth/test/**", "packages/auth/scripts/**", "packages/auth/*.config.ts",
      "scripts/check-sso-paths.mjs", "test/fixtures/sso-unguarded/**",
    ],
    checks: [
      { id: "G-S3.1", how: "test", requires: ["local-services"], desc: "TC-S3.T1.a 권한 칼럼 입력 무시 (네 DB)", cmd: 'pnpm -C packages/auth test -t "TC-S3.T1.a"' },
      { id: "G-S3.2", how: "test", requires: ["local-services"], desc: "TC-S3.T1.b 이메일 인증 전 로그인 거부 (네 DB)", cmd: 'pnpm -C packages/auth test -t "TC-S3.T1.b"' },
      { id: "G-S3.3", how: "test", desc: "TC-S3.T1.c 세션 쿠키 속성", cmd: 'pnpm -C packages/auth test -t "TC-S3.T1.c"' },
      { id: "G-S3.4", how: "cmd", desc: "TC-S3.T1.d SSO 공개 관리 경로 차단 (음성 대조 포함)", cmd: "node scripts/check-sso-paths.mjs && node scripts/check-sso-paths.mjs --fixture test/fixtures/sso-unguarded --expect-fail" },
      { id: "G-S3.5", how: "test", desc: "TC-S3.T2.a 콘솔 인증 링크로 인증 완료", cmd: 'pnpm -C packages/auth test -t "TC-S3.T2.a"' },
      { id: "G-S3.6", how: "test", requires: ["local-services"], desc: "TC-S3.T2.b SMTP 어댑터 → mailpit", cmd: "pnpm -C packages/auth test:smtp" },
      { id: "G-S3.7", how: "test", desc: "TC-S3.T2.c Resend·Cloudflare 요청과 오류 전달", cmd: 'pnpm -C packages/auth test -t "TC-S3.T2.c"' },
      { id: "G-S3.8", how: "test", desc: "TC-S3.T2.d 재설정 토큰 1회용", cmd: 'pnpm -C packages/auth test -t "TC-S3.T2.d"' },
      { id: "G-S3.9", how: "test", requires: ["local-services"], desc: "TC-S3.T3.a 같은 IP 반복 로그인 실패 → 429 (네 DB)", cmd: 'pnpm -C packages/auth test -t "TC-S3.T3.a"' },
      { id: "G-S3.10", how: "test", desc: "TC-S3.T3.b 비신뢰 출처 X-Forwarded-For 무시", cmd: 'pnpm -C packages/auth test -t "TC-S3.T3.b"' },
      { id: "G-S3.11", how: "test", desc: "TC-S3.T3.c 신뢰 프록시 뒤 클라이언트별 계산", cmd: 'pnpm -C packages/auth test -t "TC-S3.T3.c"' },
      { id: "G-S3.12", how: "json", desc: "Better Auth 버전 고정", file: "packages/auth/package.json", path: "dependencies.better-auth", op: "==", value: "1.7.7" },
      // 권한 칼럼 다섯은 packages/db 의 USER_ADDITIONAL_FIELDS 에 정의되고 auth 구성이 AUTH_SCHEMA_OPTIONS 로 그대로 쓴다.
      // 칼럼 이름과 input: false 가 한 줄에 있는 정의만 센다 (주석·TABLES 의 칼럼 정의는 걸리지 않는다).
      { id: "G-S3.13", how: "grep", desc: "권한 칼럼 다섯 input: false", pattern: "(role|status|monthlyLimitUsd|maxKeys|isBootstrapAdmin): \\{ type: [^}]*input:\\s*false", in: ["packages/db/src/schema/common.ts"], op: "==", limit: 5 },
      { id: "G-S3.14", how: "test", desc: "TC-S3.T1.e 구성과 스키마가 같은 옵션", cmd: 'pnpm -C packages/auth test -t "TC-S3.T1.e"' },
      { id: "G-S3.15", how: "test", desc: "TC-S3.T2.e 메일 전송 시간으로 계정 존재 노출 없음", cmd: 'pnpm -C packages/auth test -t "TC-S3.T2.e"' },
      { id: "G-S3.16", how: "test", desc: "TC-S3.T3.d 감싼 handler 만 내보냄", cmd: 'pnpm -C packages/auth test -t "TC-S3.T3.d"' },
      { id: "G-S3.17", how: "test", desc: "TC-S3.T1.f 짧은 secret 거부", cmd: 'pnpm -C packages/auth test -t "TC-S3.T1.f"' },
      { id: "G-S3.18", how: "test", desc: "TC-S3.T2.f 운영에서 콘솔 어댑터 거부", cmd: 'pnpm -C packages/auth test -t "TC-S3.T2.f"' },
      { id: "G-S3.19", how: "test", desc: "TC-S3.T1.d 관리 경로 404 (대조: 차단 없으면 404 아님)", cmd: 'pnpm -C packages/auth test -t "TC-S3.T1.d"' },
    ],
  },
  S4: {
    needs: ["S3"],
    waivable: false,
    outputs: [
      "packages/runtime/src/**", "packages/runtime/test/**", "packages/runtime/scripts/**", "packages/runtime/*.config.ts",
      "apps/server/src/**", "apps/server/test/**", "apps/server/scripts/**", "apps/server/*.config.ts",
      "apps/web/src/**", "apps/web/static/**", "apps/web/svelte.config.js", "apps/web/vite.config.ts",
      "tsconfig.json", "apps/*/tsconfig.json", "packages/*/tsconfig.json",
    ],
    checks: [
      { id: "G-S4.1", how: "test", requires: ["local-services"], desc: "TC-S4.T1.a job_leases 동시 임대는 하나만", cmd: 'pnpm -C packages/runtime test:db -t "TC-S4.T1.a" --db mysql,pg' },
      { id: "G-S4.2", how: "test", requires: ["local-services"], desc: "TC-S4.T1.b 만료 임대는 다른 인스턴스가", cmd: 'pnpm -C packages/runtime test:db -t "TC-S4.T1.b" --db mysql,pg' },
      { id: "G-S4.3", how: "test", desc: "TC-S4.T1.c Workers clientIp 는 CF-Connecting-IP", cmd: 'pnpm -C packages/runtime test -t "TC-S4.T1.c"' },
      { id: "G-S4.4", how: "test", desc: "TC-S4.T2.a Node ↔ Workers 암호문 교차 복호화", cmd: "pnpm -C packages/runtime test:cross-runtime" },
      { id: "G-S4.5", how: "test", desc: "TC-S4.T2.b 변조 암호문 거부", cmd: 'pnpm -C packages/runtime test -t "TC-S4.T2.b"' },
      { id: "G-S4.6", how: "test", desc: "TC-S4.T2.c 32바이트 아닌 키 거부", cmd: 'pnpm -C packages/runtime test -t "TC-S4.T2.c"' },
      { id: "G-S4.7", how: "test", desc: "TC-S4.T3.a 깊은 주소는 SPA, /api 는 JSON 404", cmd: 'pnpm -C apps/server test -t "TC-S4.T3.a"' },
      { id: "G-S4.8", how: "test", desc: "TC-S4.T3.b Node·Workers 같은 빌드 제공", cmd: 'pnpm -C apps/server test:both-runtimes -t "TC-S4.T3.b"' },
      { id: "G-S4.9", how: "cmd", desc: "TC-S4.T3.c SPA 빌드에 서버 산출 없음", cmd: "pnpm -C apps/web build && test ! -d apps/web/build/server" },
      { id: "G-S4.10", how: "test", desc: "TC-S4.T4.a 설치 토큰 1회용", cmd: 'pnpm -C apps/server test -t "TC-S4.T4.a"' },
      { id: "G-S4.11", how: "test", desc: "TC-S4.T4.b 틀린 설치 토큰 거부", cmd: 'pnpm -C apps/server test -t "TC-S4.T4.b"' },
      { id: "G-S4.12", how: "test", desc: "TC-S4.T4.c 설치 토큰 원문이 DB 에 없음", cmd: 'pnpm -C apps/server test -t "TC-S4.T4.c"' },
      { id: "G-S4.13", how: "test", desc: "TC-S4.T4.d 관리자가 있으면 토큰 없음", cmd: 'pnpm -C apps/server test -t "TC-S4.T4.d"' },
      { id: "G-S4.14", how: "grep", desc: "SPA 모드 고정", pattern: "export const ssr = false", in: ["apps/web/src/routes/+layout.ts"], op: "==", limit: 1 },
      { id: "G-S4.15", how: "test", requires: ["local-services"], desc: "TC-S4.T1.d DB 세션 시간대 UTC 강제", cmd: 'pnpm -C packages/runtime test:db -t "TC-S4.T1.d" --db mysql,mariadb,pg' },
      { id: "G-S4.16", how: "test", desc: "TC-S4.T1.e clientIp 가 null 이면 시작 거부", cmd: 'pnpm -C packages/runtime test -t "TC-S4.T1.e"' },
      { id: "G-S4.17", how: "cmd", desc: "TC-S4.T3.d 모든 패키지 타입 검사", cmd: "pnpm -r typecheck" },
      { id: "G-S4.18", how: "test", desc: "TC-S4.T2.d 다른 AAD 로 복호화 거부", cmd: 'pnpm -C packages/runtime test -t "TC-S4.T2.d"' },
      { id: "G-S4.19", how: "test", desc: "TC-S4.T3.e /api 본문 64KB 상한 (Node·Workers)", cmd: 'pnpm -C apps/server test -t "TC-S4.T3.e" && pnpm -C apps/server test:both-runtimes -t "TC-S4.T3.e"' },
      { id: "G-S4.20", how: "test", desc: "TC-S4.T3.f 보안 헤더와 SPA CSP (Node·Workers)", cmd: 'pnpm -C apps/server test:both-runtimes -t "TC-S4.T3.f"' },
      { id: "G-S4.21", how: "test", desc: "TC-S4.T4.e 설치 전 가입 403·email_taken 409", cmd: 'pnpm -C apps/server test -t "TC-S4.T4.e"' },
      { id: "G-S4.22", how: "test", requires: ["local-services"], desc: "TC-S4.T4.f 동시 설치 10건 → 관리자 하나 (SQLite·MySQL·PG)", cmd: 'pnpm -C apps/server test:db -t "TC-S4.T4.f" --db sqlite,mysql,pg' },
    ],
  },
  S5: {
    needs: ["S4"],
    waivable: false,
    outputs: [
      "packages/omniroute/src/**", "packages/omniroute/test/**", "packages/omniroute/*.config.ts",
      "tests/contract/**", "apps/server/src/setup/omniroute.ts",
      "apps/server/test/contract/**", "apps/server/vitest.contract.config.ts",
    ],
    // 계약 테스트는 tests/contract 의 OmniRoute 컨테이너(127.0.0.1:20170)를 띄우고 돈다 (tests/contract/run.mjs).
    checks: [
      { id: "G-S5.1", how: "test", requires: ["local-services"], desc: "TC-S5.T1.a 계약 환경이 0단계 실측값 재현", cmd: 'pnpm test:contract -t "TC-S5.T1.a"' },
      { id: "G-S5.2", how: "test", requires: ["local-services"], desc: "TC-S5.T2.a 키 없는 /v1 → 401", cmd: 'pnpm test:contract -t "TC-S5.T2.a"' },
      { id: "G-S5.3", how: "test", requires: ["local-services"], desc: "TC-S5.T2.b 생성 → 끄기 → 예산 → 켜기 → 요청", cmd: 'pnpm test:contract -t "TC-S5.T2.b"' },
      { id: "G-S5.4", how: "test", requires: ["local-services"], desc: "TC-S5.T2.c 끈 키 즉시 거부", cmd: 'pnpm test:contract -t "TC-S5.T2.c"' },
      { id: "G-S5.5", how: "test", requires: ["local-services"], desc: "TC-S5.T2.d 예산 초과 429 BUDGET_EXCEEDED", cmd: 'pnpm test:contract -t "TC-S5.T2.d"' },
      { id: "G-S5.6", how: "test", requires: ["local-services"], desc: "TC-S5.T2.e 키별 분석 비용 (스트리밍 포함)", cmd: 'pnpm test:contract -t "TC-S5.T2.e"' },
      { id: "G-S5.7", how: "test", requires: ["local-services"], desc: "TC-S5.T2.f 응답 형식 변화 → 오류", cmd: 'pnpm test:contract -t "TC-S5.T2.f"' },
      { id: "G-S5.8", how: "test", requires: ["local-services"], desc: "TC-S5.T2.g 쿠키 변경 요청에 Origin", cmd: 'pnpm test:contract -t "TC-S5.T2.g"' },
      // apps/server/test/app.test.ts 의 "/api/keys/1" 은 우리 서버의 모르는 /api 경로가 JSON 404 인지 보는 요청이다 (OmniRoute 호출 아님)
      { id: "G-S5.9", how: "grep", desc: "TC-S5.T2.h 어댑터 밖 OmniRoute 관리 호출 0", pattern: "/api/(keys|usage)", in: ["apps", "packages"], exclude: ["packages/omniroute/**", "apps/server/test/app.test.ts"], op: "==", limit: 0 },
      { id: "G-S5.10", how: "test", requires: ["local-services"], desc: "TC-S5.T3.a 설치 뒤 토큰 암호화 저장", cmd: 'pnpm test:contract -t "TC-S5.T3.a"' },
      { id: "G-S5.11", how: "test", requires: ["local-services"], desc: "TC-S5.T3.b 저장 토큰 범위 = V10 minScope", cmd: 'pnpm test:contract -t "TC-S5.T3.b"' },
      { id: "G-S5.12", how: "test", requires: ["local-services"], desc: "TC-S5.T3.c 틀린 비밀번호 → manual_required, 관리자는 생성", cmd: 'pnpm test:contract -t "TC-S5.T3.c"' },
      { id: "G-S5.13", how: "grep", desc: "OmniRoute 버전 고정 (태그 + digest)", pattern: "diegosouzapw/omniroute:3\\.8\\.51@sha256:", in: ["tests/contract/docker-compose.yml"], op: "==", limit: 1 },
      { id: "G-S5.14", how: "test", requires: ["local-services"], desc: "TC-S5.T2.i 어댑터는 키 scopes 를 보내지 않음", cmd: 'pnpm test:contract -t "TC-S5.T2.i"' },
      { id: "G-S5.15", how: "test", requires: ["local-services"], desc: "TC-S5.T3.d 토큰 붙여 넣기는 관리자·write 만", cmd: 'pnpm test:contract -t "TC-S5.T3.d"' },
      { id: "G-S5.16", how: "test", requires: ["local-services"], desc: "TC-S5.T2.j 월 예산 0 거부 (OmniRoute 0 = 무제한 대조)", cmd: 'pnpm test:contract -t "TC-S5.T2.j"' },
      { id: "G-S5.17", how: "test", requires: ["local-services"], desc: "TC-S5.T2.k 리다이렉트를 따라가지 않음", cmd: 'pnpm test:contract -t "TC-S5.T2.k"' },
    ],
  },
  S6: {
    needs: ["S5"],
    waivable: false,
    outputs: ["scripts/init.mjs", ".env.example", "docker-compose.yml", "deploy/**", "apps/server/Dockerfile", "apps/server/wrangler.toml", "tests/e2e/**"],
    checks: [],
  },
  S7: {
    needs: ["S6"],
    waivable: false,
    outputs: [".github/workflows/ci.yml", "scripts/check-ci-matrix.mjs"],
    checks: [],
  },
};
